// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import {application} from "./application";

import LayoutController from "./layout_controller";
application.register("layout", LayoutController);

import DialogController from "./dialog_controller";
application.register("dialog", DialogController);

import HotkeysController from "./hotkeys_controller";
application.register("hotkeys", HotkeysController);

import FlashController from "./flash_controller";
application.register("flash", FlashController);

import ConnectedReactController from "./connected_react_controller";
application.register("connected-react", ConnectedReactController);

import TagRulesController from "./tag_rules_controller";
application.register("tag-rules", TagRulesController);
