################################################################################
#
# Top level config
#
################################################################################

root: true
# have to include `plugin:react/recommended` to avoid errors
extends:
  - eslint:all
  - plugin:eslint-plugin-jsx-a11y/recommended
  - plugin:fp/recommended
  - plugin:import/errors
  - plugin:react/all
  - plugin:@typescript-eslint/all
  - ./.eslint_wishlist.yml
  - ./.eslint_todo.yml
plugins: [eslint-plugin-jsx-a11y, fp, import, react, '@typescript-eslint']
parserOptions:
  project: ['./tsconfig-test.json']
  sourceType: module
  ecmaVersion: 2018
  ecmaFeatures:
    jsx: true
env:
  browser: true
  es6: true
  node: true
globals:
  $: true
settings:
  import/resolver:
    typescript: {}
    node:
      moduleDirectory: [app/javascript, node_modules, spec/javascript]
      extensions: [.js, .ts, .tsx]
  react:
    version: '16.0'

parser: '@typescript-eslint/parser'

rules:

  ##############################################################################
  #
  # Rules that depart from eslint defaults
  #
  ##############################################################################

  # https://github.com/typescript-eslint/typescript-eslint/issues/5807
  '@typescript-eslint/no-misused-promises': off

  '@typescript-eslint/indent': [error, 2, { SwitchCase: 0 }]
  arrow-parens: [error, as-needed]
  brace-style: [error, 1tbs, { allowSingleLine: true }]
  '@typescript-eslint/brace-style': [error, 1tbs, { allowSingleLine: true }]
  camelcase: [error, { allow: ['^UNSAFE_'] }]
  comma-dangle: [error, always-multiline]
  '@typescript-eslint/comma-dangle': [error, always-multiline]
  '@typescript-eslint/consistent-indexed-object-style': [error, index-signature]
  func-style: [error, declaration]
  function-call-argument-newline: [error, consistent]
  function-paren-newline: [error, consistent]
  id-length: [error, { exceptions: [_, $] }]
  indent: [error, 2]
  jsx-quotes: [error, prefer-single]
  max-statements-per-line: [error, { max: 2 }]
  multiline-ternary: [error, never]
  newline-per-chained-call: [error, { ignoreChainWithDepth: 3 }]
  # https://github.com/eslint/typescript-eslint-parser/issues/465
  no-extra-parens: off
  # no-extra-parens: [error, all, { nestedBinaryExpressions: false, ignoreJSX: 'multi-line' }]
  no-multiple-empty-lines: [error, { max: 1, maxEOF: 0, maxBOF: 0 }]
  no-underscore-dangle: [error, { allowAfterThis: true }]
  object-curly-newline: [error, { consistent: true }]
  object-property-newline: [error, { allowMultiplePropertiesPerLine: true }]
  one-var: [error, never]
  padded-blocks: [error, never]
  prefer-arrow-callback: [error, { allowNamedFunctions: true }]
  prefer-destructuring: [error, { array: false }]
  quote-props: [error, as-needed, { keywords: true }]
  quotes: [error, single, {avoidEscape: true}]
  react/jsx-indent-props: [error, 2]
  react/jsx-indent: [error, 2]
  react/jsx-wrap-multilines: [error, { declaration: false }]
  space-before-function-paren: [error, { anonymous: always, named: never }]
  '@typescript-eslint/space-before-function-paren': [error, { anonymous: always, named: never }]
  spaced-comment: [error, always, { markers: [=] }]

  ##############################################################################
  #
  # Rules we might want to enable
  #
  ##############################################################################

  '@typescript-eslint/keyword-spacing': off

  ##############################################################################
  #
  # Rules we don't want to enable
  #
  ##############################################################################

  '@typescript-eslint/class-methods-use-this': off
  array-element-newline: off
  capitalized-comments: off
  line-comment-position: off
  no-inline-comments: off
  no-prototype-builtins: off
  no-ternary: off
  no-undefined: off
  react/jsx-filename-extension: off
  react/jsx-handler-names: off
  react/jsx-max-props-per-line: off
  react/jsx-newline: off
  react/jsx-no-bind: off
  react/jsx-one-expression-per-line: off
  react/prefer-read-only-props: off
  require-jsdoc: off
