// This configuration was generated by `exe/eslint_autogen`
// on 2026-08-26 01:32:05 UTC.
// The point is for the user to remove these configuration records
// one by one as the offenses are removed from the code base.

import type {Linter} from "eslint";

const config: Linter.Config[] = [
  // Offense count: 19
  {
    files: [
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/helpers/ajax.ts",
      "app/javascript/helpers/request.ts",
      "app/javascript/helpers/to_english.ts",
      "app/javascript/tag/action_creators.ts",
      "app/javascript/tag/selectors.ts",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/sub_tasks_table.tsx",
      "app/javascript/task/selectors.ts",
    ],
    rules: {
      "@stylistic/arrow-parens": "off",
    },
  },
  // Offense count: 14
  {
    files: [
      "app/javascript/helpers/debug.ts",
      "app/javascript/tag/selectors.ts",
      "app/javascript/task/components/sub_tasks_table.tsx",
      "spec/javascript/support/factories/task.ts",
      "spec/javascript/task/containers/focus_view_spec.tsx",
      "spec/javascript/task/containers/list_view_spec.tsx",
      "spec/javascript/task/containers/show_view_spec.tsx",
    ],
    rules: {
      "@stylistic/function-paren-newline": "off",
    },
  },
  // Offense count: 11
  {
    files: [
      "app/javascript/@types/state.d.ts",
      "app/javascript/@types/timeframe.d.ts",
    ],
    rules: {
      "@stylistic/indent-binary-ops": "off",
    },
  },
  // Offense count: 52
  {
    files: [
      "app/javascript/helpers/debug.ts",
      "app/javascript/tag/components/button.tsx",
      "app/javascript/tag/components/buttons.tsx",
      "app/javascript/task/components/delete_button.tsx",
      "app/javascript/task/components/done_button.tsx",
      "app/javascript/task/components/draggable_task_row.tsx",
      "app/javascript/task/components/edit_title_form.tsx",
      "app/javascript/task/components/focus_view.tsx",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/components/main_buttons.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/show_view.tsx",
      "app/javascript/task/components/sub_tasks_table.tsx",
      "app/javascript/task/components/task_row.tsx",
      "app/javascript/task/components/task_title.tsx",
      "spec/javascript/support/factories/task.ts",
    ],
    rules: {
      "@stylistic/member-delimiter-style": "off",
    },
  },
  // Offense count: 6
  {
    files: [
      "app/javascript/@types/globals.d.ts",
      "app/javascript/controllers/index.ts",
      "app/javascript/helpers/authenticity_token.ts",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/containers/parent_task_bread_crumbs.tsx",
    ],
    rules: {
      "@stylistic/multiline-comment-style": "off",
    },
  },
  // Offense count: 20
  {
    files: [
      "app/javascript/helpers/debug.ts",
      "app/javascript/helpers/to_english.ts",
      "app/javascript/tag/components/button.tsx",
      "app/javascript/tag/selectors.ts",
      "app/javascript/task/components/done_button.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/task_row.tsx",
    ],
    rules: {
      "@stylistic/multiline-ternary": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/task/components/sub_tasks_table.tsx",
    ],
    rules: {
      "@stylistic/no-extra-parens": "off",
    },
  },
  // Offense count: 6
  {
    files: [
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/application.tsx",
      "app/javascript/crash_site_onerror.ts",
      "app/javascript/helpers/debug.ts",
    ],
    rules: {
      "@stylistic/no-trailing-spaces": "off",
    },
  },
  // Offense count: 12
  {
    files: [
      "app/javascript/@types/globals.d.ts",
      "app/javascript/helpers/grab.ts",
      "app/javascript/task/components/sub_tasks_table.tsx",
    ],
    rules: {
      "@stylistic/object-curly-spacing": "off",
    },
  },
  // Offense count: 11
  {
    files: [
      "app/javascript/@types/state.d.ts",
      "app/javascript/@types/timeframe.d.ts",
    ],
    rules: {
      "@stylistic/operator-linebreak": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/helpers/debug.ts",
    ],
    rules: {
      "@stylistic/padded-blocks": "off",
    },
  },
  // Offense count: 7
  {
    files: [
      "app/javascript/@types/state.d.ts",
      "app/javascript/@types/tag.d.ts",
      "app/javascript/@types/task.d.ts",
      "app/javascript/@types/turbo.d.ts",
      "app/javascript/task/components/edit_title_form.tsx",
    ],
    rules: {
      "@stylistic/semi": "off",
    },
  },
  // Offense count: 4
  {
    files: [
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/await-thenable": "off",
    },
  },
  // Offense count: 5
  {
    files: [
      "app/javascript/task/components/focus_view.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "spec/javascript/support/fake_notification.ts",
    ],
    rules: {
      "@typescript-eslint/class-methods-use-this": "off",
    },
  },
  // Offense count: 15
  {
    files: [
      "app/javascript/helpers/debug.ts",
      "spec/javascript/helpers/debug_spec.ts",
      "spec/javascript/setup.ts",
      "spec/javascript/support/shims.ts",
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/consistent-type-assertions": "off",
    },
  },
  // Offense count: 59
  {
    files: [
      "app/javascript/@types/globals.d.ts",
      "app/javascript/@types/state.d.ts",
      "app/javascript/@types/tag.d.ts",
      "app/javascript/@types/task.d.ts",
      "app/javascript/@types/timeframe.d.ts",
      "app/javascript/@types/turbo.d.ts",
      "app/javascript/@types/user.d.ts",
      "app/javascript/_common/create_basic_reducer.ts",
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/helpers/request.ts",
      "app/javascript/route/reducer.ts",
      "app/javascript/tag/components/button.tsx",
      "app/javascript/tag/components/buttons.tsx",
      "app/javascript/tag/containers/buttons.ts",
      "app/javascript/task/components/delete_button.tsx",
      "app/javascript/task/components/done_button.tsx",
      "app/javascript/task/components/draggable_task_row.tsx",
      "app/javascript/task/components/edit_icon.tsx",
      "app/javascript/task/components/edit_title_form.tsx",
      "app/javascript/task/components/focus_view.tsx",
      "app/javascript/task/components/link.tsx",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/components/main_buttons.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/show_view.tsx",
      "app/javascript/task/components/sub_tasks_table.tsx",
      "app/javascript/task/components/table_headers.tsx",
      "app/javascript/task/components/task_display.tsx",
      "app/javascript/task/components/task_row.tsx",
      "app/javascript/task/components/task_title.tsx",
      "app/javascript/task/containers/parent_task_bread_crumbs.tsx",
      "app/javascript/task/selectors.ts",
    ],
    rules: {
      "@typescript-eslint/consistent-type-definitions": "off",
    },
  },
  // Offense count: 44
  {
    files: [
      "app/javascript/_common/create_app_store.ts",
      "app/javascript/_common/create_basic_reducer.ts",
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/crash_site_onerror.ts",
      "app/javascript/helpers/ajax.ts",
      "app/javascript/helpers/debug.ts",
      "app/javascript/route/action_creators.ts",
      "app/javascript/route/reducer.ts",
      "app/javascript/tag/action_creators.ts",
      "app/javascript/tag/containers/buttons.ts",
      "app/javascript/tag/reducer.ts",
      "app/javascript/tag/selectors.ts",
      "app/javascript/task/action_creators.ts",
      "app/javascript/task/components/delete_button.tsx",
      "app/javascript/task/components/main_buttons.tsx",
      "app/javascript/task/components/task_display.tsx",
      "app/javascript/task/containers/focus_view.ts",
      "app/javascript/task/containers/list_view.ts",
      "app/javascript/task/containers/parent_task_bread_crumbs.tsx",
      "app/javascript/task/containers/show_view.ts",
      "app/javascript/task/reducer.ts",
      "spec/javascript/task/components/focus_view_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/explicit-function-return-type": "off",
    },
  },
  // Offense count: 14
  {
    files: [
      "app/javascript/_common/create_app_store.ts",
      "app/javascript/_common/create_basic_reducer.ts",
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/helpers/ajax.ts",
      "app/javascript/helpers/debug.ts",
      "app/javascript/route/action_creators.ts",
      "app/javascript/tag/action_creators.ts",
      "app/javascript/task/action_creators.ts",
      "app/javascript/task/components/delete_button.tsx",
      "app/javascript/task/components/main_buttons.tsx",
      "app/javascript/task/components/task_display.tsx",
    ],
    rules: {
      "@typescript-eslint/explicit-module-boundary-types": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/crash_site_onerror.ts",
    ],
    rules: {
      "@typescript-eslint/max-params": "off",
    },
  },
  // Offense count: 2
  {
    files: [
      "app/javascript/controllers/react_controller.tsx",
      "spec/javascript/support/fake_notification.ts",
    ],
    rules: {
      "@typescript-eslint/member-ordering": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/crash_site_onerror.ts",
    ],
    rules: {
      "@typescript-eslint/no-base-to-string": "off",
    },
  },
  // Offense count: 19
  {
    files: [
      "app/javascript/_common/create_basic_reducer.ts",
      "app/javascript/task/components/postpone_button.tsx",
      "spec/javascript/route/reducer_spec.ts",
      "spec/javascript/tag/reducer_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/reducer_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/no-confusing-void-expression": "off",
    },
  },
  // Offense count: 12
  {
    files: [
      "app/javascript/_common/create_app_store.ts",
      "app/javascript/tag/containers/buttons.ts",
      "app/javascript/task/components/edit_title_form.tsx",
      "app/javascript/task/containers/focus_view.ts",
      "app/javascript/task/containers/list_view.ts",
      "app/javascript/task/containers/parent_task_bread_crumbs.tsx",
      "app/javascript/task/containers/show_view.ts",
      "spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx",
      "spec/javascript/task/containers/show_view_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/no-deprecated": "off",
    },
  },
  // Offense count: 13
  {
    files: [
      "app/javascript/@types/globals.d.ts",
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/helpers/debug.ts",
      "app/javascript/helpers/request.ts",
      "spec/javascript/helpers/debug_spec.ts",
      "spec/javascript/setup.ts",
      "spec/javascript/support/factories/state.ts",
      "spec/javascript/support/shims.ts",
    ],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/helpers/request.ts",
    ],
    rules: {
      "@typescript-eslint/no-floating-promises": "off",
    },
  },
  // Offense count: 4
  {
    files: [
      "app/javascript/task/action_creators.ts",
    ],
    rules: {
      "@typescript-eslint/no-misused-promises": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/_common/create_merged_reducer.ts",
    ],
    rules: {
      "@typescript-eslint/no-redundant-type-constituents": "off",
    },
  },
  // Offense count: 2
  {
    files: [
      "app/javascript/task/components/task_display.tsx",
      "app/javascript/task/selectors.ts",
    ],
    rules: {
      "@typescript-eslint/no-unnecessary-condition": "off",
    },
  },
  // Offense count: 2
  {
    files: [
      "app/javascript/_common/create_basic_reducer.ts",
      "app/javascript/helpers/debug.ts",
    ],
    rules: {
      "@typescript-eslint/no-unnecessary-type-parameters": "off",
    },
  },
  // Offense count: 6
  {
    files: [
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/task/action_creators.ts",
    ],
    rules: {
      "@typescript-eslint/no-unsafe-argument": "off",
    },
  },
  // Offense count: 13
  {
    files: [
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/helpers/debug.ts",
      "app/javascript/task/action_creators.ts",
      "spec/javascript/support/factories/state.ts",
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/no-unsafe-assignment": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/no-unsafe-call": "off",
    },
  },
  // Offense count: 8
  {
    files: [
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/helpers/debug.ts",
      "spec/javascript/helpers/debug_spec.ts",
      "spec/javascript/setup.ts",
      "spec/javascript/support/shims.ts",
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/no-unsafe-member-access": "off",
    },
  },
  // Offense count: 3
  {
    files: [
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/helpers/debug.ts",
    ],
    rules: {
      "@typescript-eslint/no-unsafe-return": "off",
    },
  },
  // Offense count: 15
  {
    files: [
      "app/javascript/helpers/debug.ts",
      "spec/javascript/helpers/debug_spec.ts",
      "spec/javascript/setup.ts",
      "spec/javascript/support/shims.ts",
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/no-unsafe-type-assertion": "off",
    },
  },
  // Offense count: 2
  {
    files: [
      "app/javascript/crash_site_onerror.ts",
    ],
    rules: {
      "@typescript-eslint/no-use-before-define": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/prefer-destructuring": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/@types/globals.d.ts",
    ],
    rules: {
      "@typescript-eslint/prefer-function-type": "off",
    },
  },
  // Offense count: 5
  {
    files: [
      "app/javascript/task/components/task_row.tsx",
      "app/javascript/task/reducer.ts",
      "spec/javascript/support/factories/state.ts",
      "spec/javascript/support/factories/task.ts",
    ],
    rules: {
      "@typescript-eslint/prefer-nullish-coalescing": "off",
    },
  },
  // Offense count: 3
  {
    files: [
      "app/javascript/crash_site_onerror.ts",
      "app/javascript/tag/reducer.ts",
      "app/javascript/task/components/task_display.tsx",
    ],
    rules: {
      "@typescript-eslint/prefer-optional-chain": "off",
    },
  },
  // Offense count: 6
  {
    files: [
      "app/javascript/helpers/ajax.ts",
      "spec/javascript/support/fake_notification.ts",
    ],
    rules: {
      "@typescript-eslint/promise-function-async": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/crash_site_onerror.ts",
    ],
    rules: {
      "@typescript-eslint/restrict-template-expressions": "off",
    },
  },
  // Offense count: 24
  {
    files: [
      "app/javascript/crash_site_onerror.ts",
      "app/javascript/helpers/debug.ts",
      "app/javascript/tag/components/buttons.tsx",
      "app/javascript/task/action_creators.ts",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/components/show_view.tsx",
      "app/javascript/task/components/task_display.tsx",
      "app/javascript/task/components/task_row.tsx",
      "app/javascript/task/components/task_title.tsx",
      "app/javascript/task/reducer.ts",
      "app/javascript/task/selectors.ts",
      "spec/javascript/support/factories/task.ts",
    ],
    rules: {
      "@typescript-eslint/strict-boolean-expressions": "off",
    },
  },
  // Offense count: 31
  {
    files: [
      "app/javascript/_common/globals.ts",
      "app/javascript/tag/action_creators.ts",
      "app/javascript/task/action_creators.ts",
      "spec/javascript/app_store_spec.ts",
      "spec/javascript/support/fake_notification.ts",
      "spec/javascript/task/components/focus_view_spec.tsx",
      "spec/javascript/task/components/list_view_spec.tsx",
      "spec/javascript/task/components/postpone_button_spec.tsx",
      "spec/javascript/task/components/show_view_spec.tsx",
      "spec/javascript/task/components/sub_tasks_table_spec.tsx",
      "spec/javascript/task/components/task_row_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/strict-void-return": "off",
    },
  },
  // Offense count: 21
  {
    files: [
      "app/javascript/tag/components/buttons.tsx",
      "app/javascript/task/components/delete_button.tsx",
      "app/javascript/task/components/done_button.tsx",
      "app/javascript/task/components/edit_title_form.tsx",
      "app/javascript/task/components/focus_view.tsx",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/task_row.tsx",
    ],
    rules: {
      "@typescript-eslint/unbound-method": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/support/vitest.d.ts",
    ],
    rules: {
      "@typescript-eslint/unified-signatures": "off",
    },
  },
  // Offense count: 43
  {
    files: [
      "app/javascript/helpers/ajax.ts",
      "app/javascript/helpers/to_english.ts",
      "app/javascript/tag/action_creators.ts",
      "app/javascript/tag/selectors.ts",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/sub_tasks_table.tsx",
      "app/javascript/task/selectors.ts",
      "spec/javascript/helpers/grab_spec.ts",
      "spec/javascript/tag/action_creators_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/components/focus_view_spec.tsx",
      "spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx",
      "spec/javascript/task/containers/show_view_spec.tsx",
    ],
    rules: {
      "arrow-body-style": "off",
    },
  },
  // Offense count: 15
  {
    files: [
      "app/javascript/@types/globals.d.ts",
      "app/javascript/controllers/dialog_controller.ts",
      "app/javascript/helpers/authenticity_token.ts",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/components/task_row.tsx",
      "app/javascript/task/containers/parent_task_bread_crumbs.tsx",
      "spec/javascript/helpers/debug_spec.ts",
      "spec/javascript/setup.ts",
      "spec/javascript/support/fake_notification.ts",
    ],
    rules: {
      "capitalized-comments": "off",
    },
  },
  // Offense count: 4
  {
    files: [
      "spec/javascript/tag/selectors_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/components/list_view_spec.tsx",
    ],
    rules: {
      "max-lines-per-function": "off",
    },
  },
  // Offense count: 6
  {
    files: [
      "app/javascript/helpers/debug.ts",
      "app/javascript/task/components/list_view.tsx",
      "spec/javascript/tag/selectors_spec.ts",
      "spec/javascript/task/components/list_view_spec.tsx",
    ],
    rules: {
      "max-statements": "off",
    },
  },
  // Offense count: 2
  {
    files: [
      "app/javascript/tag/reducer.ts",
      "spec/javascript/support/factories/task.ts",
    ],
    rules: {
      "no-prototype-builtins": "off",
    },
  },
  // Offense count: 10
  {
    files: [
      "app/javascript/helpers/debug.ts",
      "app/javascript/helpers/to_english.ts",
      "app/javascript/tag/components/button.tsx",
      "app/javascript/tag/selectors.ts",
      "app/javascript/task/components/done_button.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/task_row.tsx",
    ],
    rules: {
      "no-ternary": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/helpers/request.ts",
    ],
    rules: {
      "no-void": "off",
    },
  },
  // Offense count: 132
  {
    files: [
      "app/javascript/helpers/ajax.ts",
      "app/javascript/helpers/debug.ts",
      "app/javascript/helpers/request.ts",
      "app/javascript/route/action_creators.ts",
      "app/javascript/tag/action_creators.ts",
      "app/javascript/tag/components/button.tsx",
      "app/javascript/tag/selectors.ts",
      "app/javascript/task/action_creators.ts",
      "app/javascript/task/components/delete_button.tsx",
      "app/javascript/task/components/edit_title_form.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/show_view.tsx",
      "app/javascript/task/components/sub_tasks_table.tsx",
      "app/javascript/task/components/task_display.tsx",
      "app/javascript/task/components/task_row.tsx",
      "app/javascript/task/components/task_title.tsx",
      "app/javascript/task/containers/focus_view.ts",
      "app/javascript/task/containers/list_view.ts",
      "app/javascript/task/reducer.ts",
      "app/javascript/task/selectors.ts",
      "app/javascript/timeframe/name_map.ts",
      "spec/javascript/app_reducer_spec.ts",
      "spec/javascript/app_store_spec.ts",
      "spec/javascript/route/action_creators_spec.ts",
      "spec/javascript/route/reducer_spec.ts",
      "spec/javascript/support/factories/state.ts",
      "spec/javascript/support/factories/tag.ts",
      "spec/javascript/support/factories/task.ts",
      "spec/javascript/tag/action_creators_spec.ts",
      "spec/javascript/tag/components/button_spec.tsx",
      "spec/javascript/tag/components/buttons_spec.tsx",
      "spec/javascript/tag/reducer_spec.ts",
      "spec/javascript/tag/selectors_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/components/show_view_spec.tsx",
      "spec/javascript/task/components/sub_tasks_table_spec.tsx",
      "spec/javascript/task/components/task_row_spec.tsx",
      "spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx",
      "spec/javascript/task/reducer_spec.tsx",
      "spec/javascript/task/selectors_spec.tsx",
    ],
    rules: {
      "perfectionist/sort-objects": "off",
    },
  },
  // Offense count: 7
  {
    files: [
      "app/javascript/task/action_creators.ts",
      "app/javascript/task/containers/list_view.ts",
      "app/javascript/task/reducer.ts",
      "spec/javascript/tag/action_creators_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/reducer_spec.tsx",
      "spec/javascript/task/selectors_spec.tsx",
    ],
    rules: {
      "sort-imports": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/tag/selectors_spec.ts",
    ],
    rules: {
      "vitest/max-expects": "off",
    },
  },
  // Offense count: 7
  {
    files: [
      "spec/javascript/helpers/debug_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "vitest/no-hooks": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "vitest/no-standalone-expect": "off",
    },
  },
  // Offense count: 23
  {
    files: [
      "spec/javascript/app_store_spec.ts",
      "spec/javascript/helpers/debug_spec.ts",
      "spec/javascript/helpers/grab_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/components/focus_view_spec.tsx",
      "spec/javascript/task/components/list_view_spec.tsx",
      "spec/javascript/task/components/sub_tasks_table_spec.tsx",
      "spec/javascript/task/components/task_row_spec.tsx",
      "spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx",
      "spec/javascript/task/selectors_spec.tsx",
    ],
    rules: {
      "vitest/padding-around-all": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/helpers/debug_spec.ts",
    ],
    rules: {
      "vitest/padding-around-before-each-blocks": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/helpers/debug_spec.ts",
    ],
    rules: {
      "vitest/padding-around-describe-blocks": "off",
    },
  },
  // Offense count: 22
  {
    files: [
      "spec/javascript/app_store_spec.ts",
      "spec/javascript/helpers/grab_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/components/focus_view_spec.tsx",
      "spec/javascript/task/components/list_view_spec.tsx",
      "spec/javascript/task/components/sub_tasks_table_spec.tsx",
      "spec/javascript/task/components/task_row_spec.tsx",
      "spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx",
      "spec/javascript/task/selectors_spec.tsx",
    ],
    rules: {
      "vitest/padding-around-expect-groups": "off",
    },
  },
  // Offense count: 2
  {
    files: [
      "spec/javascript/app_store_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "vitest/prefer-called-with": "off",
    },
  },
  // Offense count: 17
  {
    files: [
      "spec/javascript/tag/action_creators_spec.ts",
      "spec/javascript/tag/selectors_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx",
      "spec/javascript/task/selectors_spec.tsx",
    ],
    rules: {
      "vitest/prefer-describe-function-title": "off",
    },
  },
  // Offense count: 8
  {
    files: [
      "spec/javascript/application_spec.ts",
      "spec/javascript/tag/action_creators_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/components/focus_view_spec.tsx",
      "spec/javascript/task/containers/focus_view_spec.tsx",
      "spec/javascript/task/containers/list_view_spec.tsx",
    ],
    rules: {
      "vitest/prefer-import-in-mock": "off",
    },
  },
  // Offense count: 456
  {
    files: [
      "spec/javascript/app_reducer_spec.ts",
      "spec/javascript/app_store_spec.ts",
      "spec/javascript/application_spec.ts",
      "spec/javascript/channels/consumer_spec.ts",
      "spec/javascript/controllers/flash_controller_spec.ts",
      "spec/javascript/controllers/hotkeys_controller_spec.ts",
      "spec/javascript/helpers/debug_spec.ts",
      "spec/javascript/helpers/grab_spec.ts",
      "spec/javascript/helpers/to_english_spec.ts",
      "spec/javascript/route/action_creators_spec.ts",
      "spec/javascript/route/reducer_spec.ts",
      "spec/javascript/setup.ts",
      "spec/javascript/support/stimulus.ts",
      "spec/javascript/tag/action_creators_spec.ts",
      "spec/javascript/tag/components/button_spec.tsx",
      "spec/javascript/tag/components/buttons_spec.tsx",
      "spec/javascript/tag/reducer_spec.ts",
      "spec/javascript/tag/selectors_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/components/edit_title_form_spec.tsx",
      "spec/javascript/task/components/focus_view_spec.tsx",
      "spec/javascript/task/components/link_spec.tsx",
      "spec/javascript/task/components/list_view_spec.tsx",
      "spec/javascript/task/components/postpone_button_spec.tsx",
      "spec/javascript/task/components/show_view_spec.tsx",
      "spec/javascript/task/components/sub_tasks_table_spec.tsx",
      "spec/javascript/task/components/task_display_spec.tsx",
      "spec/javascript/task/components/task_row_spec.tsx",
      "spec/javascript/task/components/task_title_spec.tsx",
      "spec/javascript/task/containers/focus_view_spec.tsx",
      "spec/javascript/task/containers/list_view_spec.tsx",
      "spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx",
      "spec/javascript/task/containers/show_view_spec.tsx",
      "spec/javascript/task/reducer_spec.tsx",
      "spec/javascript/task/selectors_spec.tsx",
    ],
    rules: {
      "vitest/prefer-importing-vitest-globals": "off",
    },
  },
  // Offense count: 3
  {
    files: [
      "spec/javascript/helpers/to_english_spec.ts",
      "spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx",
    ],
    rules: {
      "vitest/prefer-lowercase-title": "off",
    },
  },
  // Offense count: 5
  {
    files: [
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "vitest/prefer-mock-promise-shorthand": "off",
    },
  },
  // Offense count: 56
  {
    files: [
      "spec/javascript/app_reducer_spec.ts",
      "spec/javascript/app_store_spec.ts",
      "spec/javascript/route/action_creators_spec.ts",
      "spec/javascript/route/reducer_spec.ts",
      "spec/javascript/tag/action_creators_spec.ts",
      "spec/javascript/tag/reducer_spec.ts",
      "spec/javascript/tag/selectors_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/reducer_spec.tsx",
      "spec/javascript/task/selectors_spec.tsx",
    ],
    rules: {
      "vitest/prefer-strict-equal": "off",
    },
  },
  // Offense count: 9
  {
    files: [
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "vitest/prefer-vi-mocked": "off",
    },
  },
  // Offense count: 3
  {
    files: [
      "app/javascript/application.tsx",
      "spec/javascript/support/factories/id.ts",
    ],
    rules: {
      "vitest/require-hook": "off",
    },
  },
  // Offense count: 39
  {
    files: [
      "spec/javascript/app_store_spec.ts",
      "spec/javascript/controllers/flash_controller_spec.ts",
      "spec/javascript/setup.ts",
      "spec/javascript/tag/action_creators_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/components/edit_title_form_spec.tsx",
      "spec/javascript/task/components/focus_view_spec.tsx",
      "spec/javascript/task/components/list_view_spec.tsx",
      "spec/javascript/task/components/postpone_button_spec.tsx",
      "spec/javascript/task/components/show_view_spec.tsx",
      "spec/javascript/task/components/sub_tasks_table_spec.tsx",
      "spec/javascript/task/components/task_display_spec.tsx",
      "spec/javascript/task/components/task_row_spec.tsx",
      "spec/javascript/task/components/task_title_spec.tsx",
      "spec/javascript/task/containers/focus_view_spec.tsx",
    ],
    rules: {
      "vitest/require-mock-type-parameters": "off",
    },
  },
  // Offense count: 21
  {
    files: [
      "app/javascript/tag/components/buttons.tsx",
      "app/javascript/task/components/delete_button.tsx",
      "app/javascript/task/components/done_button.tsx",
      "app/javascript/task/components/edit_title_form.tsx",
      "app/javascript/task/components/focus_view.tsx",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/task_row.tsx",
    ],
    rules: {
      "vitest/unbound-method": "off",
    },
  },
];

export default config;
