// This configuration was generated by `exe/eslint_autogen`
// on 2026-02-11 23:53:51 UTC.
// The point is for the user to remove these configuration records
// one by one as the offenses are removed from the code base.
export default [

  // Offense count: 35
  {
    files: [
      'app/javascript/helpers/ajax.ts',
      'app/javascript/helpers/request.ts',
      'app/javascript/helpers/to_english.ts',
      'app/javascript/src/_common/create_merged_reducer.ts',
      'app/javascript/src/route/helpers.ts',
      'app/javascript/src/route/routes.ts',
      'app/javascript/src/tag/action_creators.ts',
      'app/javascript/src/tag/components/edit_view.tsx',
      'app/javascript/src/tag/components/rule_row.tsx',
      'app/javascript/src/tag/selectors.ts',
      'app/javascript/src/task/bulk_store.ts',
      'app/javascript/src/task/components/list_view.tsx',
      'app/javascript/src/task/components/postpone_button.tsx',
      'app/javascript/src/task/components/sub_tasks_table.tsx',
      'app/javascript/src/task/selectors.ts',
      'app/javascript/src/task/store.ts',
      'app/javascript/src/timeframe/store.ts',
      'spec/javascript/timeframe/store_spec.ts',
    ],
    rules: { '@stylistic/arrow-parens': 'off' as const },
  },

  // Offense count: 1
  {
    files: ['app/javascript/helpers/request.ts'],
    rules: { '@stylistic/dot-location': 'off' as const },
  },

  // Offense count: 24
  {
    files: [
      'app/javascript/helpers/debug.ts',
      'app/javascript/src/tag/selectors.ts',
      'app/javascript/src/task/components/draggable_task_row.tsx',
      'app/javascript/src/task/components/sub_tasks_table.tsx',
      'spec/javascript/_test_helpers/factories/task.ts',
      'spec/javascript/tag/containers/edit_view_spec.tsx',
      'spec/javascript/task/containers/focus_view_spec.tsx',
      'spec/javascript/task/containers/list_view_spec.tsx',
      'spec/javascript/task/containers/show_view_spec.tsx',
      'spec/javascript/task/containers/tree_view_spec.tsx',
      'spec/javascript/timeframe/containers/list_view_spec.tsx',
      'spec/javascript/timeframe/store_spec.ts',
    ],
    rules: { '@stylistic/function-paren-newline': 'off' as const },
  },

  // Offense count: 7
  {
    files: ['spec/javascript/_test_helpers/enzyme_matchers.ts'],
    rules: { '@stylistic/implicit-arrow-linebreak': 'off' as const },
  },

  // Offense count: 5
  {
    files: ['app/javascript/src/task/store.ts'],
    rules: { '@stylistic/indent': 'off' as const },
  },

  // Offense count: 11
  {
    files: [
      'app/javascript/@types/state.d.ts',
      'app/javascript/@types/timeframe.d.ts',
    ],
    rules: { '@stylistic/indent-binary-ops': 'off' as const },
  },

  // Offense count: 4
  {
    files: ['spec/javascript/_test_helpers/enzyme_matchers.ts'],
    rules: { '@stylistic/max-len': 'off' as const },
  },

  // Offense count: 85
  {
    files: [
      'app/javascript/helpers/debug.ts',
      'app/javascript/src/tag/components/button.tsx',
      'app/javascript/src/tag/components/buttons.tsx',
      'app/javascript/src/tag/components/edit_view.tsx',
      'app/javascript/src/tag/components/rule_row.tsx',
      'app/javascript/src/task/components/checkbox.tsx',
      'app/javascript/src/task/components/delete_button.tsx',
      'app/javascript/src/task/components/done_button.tsx',
      'app/javascript/src/task/components/draggable_task_row.tsx',
      'app/javascript/src/task/components/edit_title_form.tsx',
      'app/javascript/src/task/components/focus_view.tsx',
      'app/javascript/src/task/components/leaf_list_item.tsx',
      'app/javascript/src/task/components/list_view.tsx',
      'app/javascript/src/task/components/main_buttons.tsx',
      'app/javascript/src/task/components/nested_list.tsx',
      'app/javascript/src/task/components/parent_list_item.tsx',
      'app/javascript/src/task/components/postpone_button.tsx',
      'app/javascript/src/task/components/show_view.tsx',
      'app/javascript/src/task/components/sub_tasks_table.tsx',
      'app/javascript/src/task/components/task_row.tsx',
      'app/javascript/src/task/components/task_title.tsx',
      'app/javascript/src/task/components/tree_view.tsx',
      'app/javascript/src/timeframe/components/list_view.tsx',
      'app/javascript/src/timeframe/components/section.tsx',
      'app/javascript/src/timeframe/components/task_row.tsx',
      'spec/javascript/_test_helpers/factories/task.ts',
    ],
    rules: { '@stylistic/member-delimiter-style': 'off' as const },
  },

  // Offense count: 9
  {
    files: [
      'app/assets/config/manifest.js',
      'app/javascript/@types/globals.d.ts',
      'app/javascript/channels/consumer.js',
      'app/javascript/controllers/index.ts',
      'app/javascript/helpers/authenticity_token.ts',
      'app/javascript/src/tag/components/rule_row.tsx',
      'app/javascript/src/task/components/list_view.tsx',
      'app/javascript/src/task/containers/parent_task_bread_crumbs.tsx',
    ],
    rules: { '@stylistic/multiline-comment-style': 'off' as const },
  },

  // Offense count: 42
  {
    files: [
      'app/javascript/helpers/debug.ts',
      'app/javascript/helpers/to_english.ts',
      'app/javascript/src/tag/components/button.tsx',
      'app/javascript/src/tag/components/rule_row.tsx',
      'app/javascript/src/tag/selectors.ts',
      'app/javascript/src/task/components/done_button.tsx',
      'app/javascript/src/task/components/postpone_button.tsx',
      'app/javascript/src/task/components/task_row.tsx',
      'app/javascript/src/timeframe/components/section.tsx',
      'app/javascript/src/timeframe/components/task_row.tsx',
      'app/javascript/src/timeframe/utils.ts',
      'spec/javascript/_test_helpers/enzyme_matchers.ts',
    ],
    rules: { '@stylistic/multiline-ternary': 'off' as const },
  },

  // Offense count: 7
  {
    files: ['spec/javascript/_test_helpers/enzyme_matchers.ts'],
    rules: { '@stylistic/no-confusing-arrow': 'off' as const },
  },

  // Offense count: 6
  {
    files: [
      'app/javascript/helpers/authenticity_token.ts',
      'app/javascript/src/tag/components/rule_row.tsx',
      'app/javascript/src/task/components/sub_tasks_table.tsx',
      'app/javascript/src/timeframe/components/table_headers.tsx',
      'spec/javascript/task/components/leaf_list_item_spec.tsx',
    ],
    rules: { '@stylistic/no-extra-parens': 'off' as const },
  },

  // Offense count: 6
  {
    files: [
      'app/javascript/helpers/debug.ts',
      'app/javascript/packs/crash_site_onerror.ts',
      'app/javascript/src/_common/create_merged_reducer.ts',
      'app/javascript/src/application.tsx',
    ],
    rules: { '@stylistic/no-trailing-spaces': 'off' as const },
  },

  // Offense count: 18
  {
    files: [
      'app/javascript/@types/globals.d.ts',
      'app/javascript/helpers/grab.ts',
      'app/javascript/src/route/routes.ts',
      'app/javascript/src/tag/components/rule_row.tsx',
      'app/javascript/src/task/components/draggable_task_row.tsx',
      'app/javascript/src/task/components/sub_tasks_table.tsx',
    ],
    rules: { '@stylistic/object-curly-spacing': 'off' as const },
  },

  // Offense count: 11
  {
    files: [
      'app/javascript/@types/state.d.ts',
      'app/javascript/@types/timeframe.d.ts',
    ],
    rules: { '@stylistic/operator-linebreak': 'off' as const },
  },

  // Offense count: 1
  {
    files: ['app/javascript/helpers/debug.ts'],
    rules: { '@stylistic/padded-blocks': 'off' as const },
  },

  // Offense count: 6
  {
    files: ['vitest.config.ts'],
    rules: { '@stylistic/quote-props': 'off' as const },
  },

  // Offense count: 1633
  {
    files: [
      'app/javascript/@types/class-autobind.d.ts',
      'app/javascript/@types/globals.d.ts',
      'app/javascript/@types/tag.d.ts',
      'app/javascript/@types/task.d.ts',
      'app/javascript/@types/timeframe.d.ts',
      'app/javascript/@types/turbo.d.ts',
      'app/javascript/@types/user.d.ts',
      'app/javascript/controllers/dialog_controller.ts',
      'app/javascript/controllers/hotkeys_controller.ts',
      'app/javascript/controllers/index.ts',
      'app/javascript/controllers/layout_controller.ts',
      'app/javascript/controllers/react_controller.tsx',
      'app/javascript/helpers/ajax.ts',
      'app/javascript/helpers/authenticity_token.ts',
      'app/javascript/helpers/debug.ts',
      'app/javascript/helpers/request.ts',
      'app/javascript/helpers/time_balancer.ts',
      'app/javascript/helpers/to_english.ts',
      'app/javascript/packs/application.ts',
      'app/javascript/packs/crash_site_onerror.ts',
      'app/javascript/packs/freeze_time.ts',
      'app/javascript/src/_common/components/authenticity_token.tsx',
      'app/javascript/src/_common/create_basic_reducer.ts',
      'app/javascript/src/_common/create_merged_reducer.ts',
      'app/javascript/src/app_reducer.ts',
      'app/javascript/src/app_store.ts',
      'app/javascript/src/application.tsx',
      'app/javascript/src/create_app_store.ts',
      'app/javascript/src/globals.ts',
      'app/javascript/src/route/action_creators.ts',
      'app/javascript/src/route/helpers.ts',
      'app/javascript/src/route/reducer.ts',
      'app/javascript/src/route/routes.ts',
      'app/javascript/src/tag/action_creators.ts',
      'app/javascript/src/tag/components/button.tsx',
      'app/javascript/src/tag/components/buttons.tsx',
      'app/javascript/src/tag/components/edit_view.tsx',
      'app/javascript/src/tag/components/rule_row.tsx',
      'app/javascript/src/tag/containers/buttons.ts',
      'app/javascript/src/tag/containers/edit_view.ts',
      'app/javascript/src/tag/reducer.ts',
      'app/javascript/src/tag/selectors.ts',
      'app/javascript/src/task/action_creators.ts',
      'app/javascript/src/task/bulk_store.ts',
      'app/javascript/src/task/components/checkbox.tsx',
      'app/javascript/src/task/components/delete_button.tsx',
      'app/javascript/src/task/components/done_button.tsx',
      'app/javascript/src/task/components/draggable_task_row.tsx',
      'app/javascript/src/task/components/edit_icon.tsx',
      'app/javascript/src/task/components/edit_title_form.tsx',
      'app/javascript/src/task/components/focus_view.tsx',
      'app/javascript/src/task/components/leaf_list_item.tsx',
      'app/javascript/src/task/components/link.tsx',
      'app/javascript/src/task/components/list_view.tsx',
      'app/javascript/src/task/components/main_buttons.tsx',
      'app/javascript/src/task/components/nested_list.tsx',
      'app/javascript/src/task/components/parent_list_item.tsx',
      'app/javascript/src/task/components/postpone_button.tsx',
      'app/javascript/src/task/components/show_view.tsx',
      'app/javascript/src/task/components/sub_tasks_table.tsx',
      'app/javascript/src/task/components/table_headers.tsx',
      'app/javascript/src/task/components/task_display.tsx',
      'app/javascript/src/task/components/task_row.tsx',
      'app/javascript/src/task/components/task_title.tsx',
      'app/javascript/src/task/components/tree_view.tsx',
      'app/javascript/src/task/containers/focus_view.ts',
      'app/javascript/src/task/containers/list_view.ts',
      'app/javascript/src/task/containers/parent_task_bread_crumbs.tsx',
      'app/javascript/src/task/containers/show_view.ts',
      'app/javascript/src/task/containers/tree_view.ts',
      'app/javascript/src/task/reducer.ts',
      'app/javascript/src/task/selectors.ts',
      'app/javascript/src/task/store.ts',
      'app/javascript/src/timeframe/components/list_view.tsx',
      'app/javascript/src/timeframe/components/section.tsx',
      'app/javascript/src/timeframe/components/table_headers.tsx',
      'app/javascript/src/timeframe/components/task_row.tsx',
      'app/javascript/src/timeframe/containers/list_view.ts',
      'app/javascript/src/timeframe/name_map.ts',
      'app/javascript/src/timeframe/store.ts',
      'app/javascript/src/timeframe/utils.ts',
      'spec/javascript/_test_helpers/enzyme_matchers.ts',
      'spec/javascript/_test_helpers/factories.ts',
      'spec/javascript/_test_helpers/factories/notification.ts',
      'spec/javascript/_test_helpers/factories/route.ts',
      'spec/javascript/_test_helpers/factories/state.ts',
      'spec/javascript/_test_helpers/factories/tag.ts',
      'spec/javascript/_test_helpers/factories/task.ts',
      'spec/javascript/_test_helpers/factories/timeframe.ts',
      'spec/javascript/_test_helpers/fake_notification.ts',
      'spec/javascript/_test_helpers/shims.ts',
      'spec/javascript/_test_helpers/vitest.d.ts',
      'spec/javascript/app_reducer_spec.ts',
      'spec/javascript/app_store_spec.ts',
      'spec/javascript/application_spec.ts',
      'spec/javascript/controllers/hotkeys_controller_spec.ts',
      'spec/javascript/helpers/assert_spec.ts',
      'spec/javascript/helpers/debug_spec.ts',
      'spec/javascript/helpers/grab_spec.ts',
      'spec/javascript/helpers/time_balancer_spec.ts',
      'spec/javascript/helpers/to_english_spec.ts',
      'spec/javascript/packs/application_spec.ts',
      'spec/javascript/route/action_creators_spec.ts',
      'spec/javascript/route/helpers_spec.ts',
      'spec/javascript/route/reducer_spec.ts',
      'spec/javascript/support/stimulus.ts',
      'spec/javascript/tag/action_creators_spec.ts',
      'spec/javascript/tag/components/button_spec.tsx',
      'spec/javascript/tag/components/buttons_spec.tsx',
      'spec/javascript/tag/components/edit_view_spec.tsx',
      'spec/javascript/tag/components/rule_row_spec.tsx',
      'spec/javascript/tag/containers/edit_view_spec.tsx',
      'spec/javascript/tag/reducer_spec.ts',
      'spec/javascript/tag/selectors_spec.ts',
      'spec/javascript/task/action_creators_spec.tsx',
      'spec/javascript/task/components/checkbox_spec.tsx',
      'spec/javascript/task/components/edit_title_form_spec.tsx',
      'spec/javascript/task/components/focus_view_spec.tsx',
      'spec/javascript/task/components/leaf_list_item_spec.tsx',
      'spec/javascript/task/components/link_spec.tsx',
      'spec/javascript/task/components/list_view_spec.tsx',
      'spec/javascript/task/components/nested_list_spec.tsx',
      'spec/javascript/task/components/parent_list_item_spec.tsx',
      'spec/javascript/task/components/postpone_button_spec.tsx',
      'spec/javascript/task/components/show_view_spec.tsx',
      'spec/javascript/task/components/sub_tasks_table_spec.tsx',
      'spec/javascript/task/components/task_display_spec.tsx',
      'spec/javascript/task/components/task_row_spec.tsx',
      'spec/javascript/task/components/task_title_spec.tsx',
      'spec/javascript/task/components/tree_view_spec.tsx',
      'spec/javascript/task/containers/focus_view_spec.tsx',
      'spec/javascript/task/containers/list_view_spec.tsx',
      'spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx',
      'spec/javascript/task/containers/show_view_spec.tsx',
      'spec/javascript/task/containers/tree_view_spec.tsx',
      'spec/javascript/task/reducer_spec.tsx',
      'spec/javascript/task/selectors_spec.tsx',
      'spec/javascript/test_helper.ts',
      'spec/javascript/timeframe/components/list_view_spec.tsx',
      'spec/javascript/timeframe/components/task_row_spec.tsx',
      'spec/javascript/timeframe/containers/list_view_spec.tsx',
      'spec/javascript/timeframe/store_spec.ts',
      'spec/javascript/timeframe/utils_spec.ts',
      'spec/support/disable_animations.js',
      'vitest.config.ts',
    ],
    rules: { '@stylistic/quotes': 'off' as const },
  },

  // Offense count: 7
  {
    files: [
      'app/javascript/@types/state.d.ts',
      'app/javascript/@types/tag.d.ts',
      'app/javascript/@types/task.d.ts',
      'app/javascript/@types/turbo.d.ts',
      'app/javascript/src/task/components/edit_title_form.tsx',
    ],
    rules: { '@stylistic/semi': 'off' as const },
  },

  // Offense count: 3
  {
    files: ['app/assets/config/manifest.js'],
    rules: { '@stylistic/spaced-comment': 'off' as const },
  },

  // Offense count: 4
  {
    files: ['spec/javascript/task/action_creators_spec.tsx'],
    rules: { '@typescript-eslint/await-thenable': 'off' as const },
  },

  // Offense count: 6
  {
    files: [
      'app/javascript/src/tag/components/rule_row.tsx',
      'app/javascript/src/task/components/focus_view.tsx',
      'app/javascript/src/task/components/postpone_button.tsx',
      'spec/javascript/_test_helpers/fake_notification.ts',
    ],
    rules: { '@typescript-eslint/class-methods-use-this': 'off' as const },
  },

  // Offense count: 2
  {
    files: [
      'spec/javascript/_test_helpers/enzyme_matchers.ts',
      'spec/javascript/_test_helpers/vitest.d.ts',
    ],
    rules: { '@typescript-eslint/consistent-indexed-object-style': 'off' as const },
  },

  // Offense count: 32
  {
    files: [
      'app/javascript/helpers/debug.ts',
      'spec/javascript/_test_helpers/enzyme_matchers.ts',
      'spec/javascript/_test_helpers/shims.ts',
      'spec/javascript/helpers/debug_spec.ts',
      'spec/javascript/task/action_creators_spec.tsx',
      'spec/javascript/task/components/leaf_list_item_spec.tsx',
      'spec/javascript/task/components/list_view_spec.tsx',
      'spec/javascript/test_helper.ts',
      'spec/javascript/timeframe/components/list_view_spec.tsx',
      'spec/javascript/timeframe/store_spec.ts',
    ],
    rules: { '@typescript-eslint/consistent-type-assertions': 'off' as const },
  },

  // Offense count: 82
  {
    files: [
      'app/javascript/@types/globals.d.ts',
      'app/javascript/@types/route.d.ts',
      'app/javascript/@types/state.d.ts',
      'app/javascript/@types/tag.d.ts',
      'app/javascript/@types/task.d.ts',
      'app/javascript/@types/timeframe.d.ts',
      'app/javascript/@types/turbo.d.ts',
      'app/javascript/@types/user.d.ts',
      'app/javascript/helpers/request.ts',
      'app/javascript/src/_common/create_basic_reducer.ts',
      'app/javascript/src/_common/create_merged_reducer.ts',
      'app/javascript/src/route/action_creators.ts',
      'app/javascript/src/route/reducer.ts',
      'app/javascript/src/route/routes.ts',
      'app/javascript/src/tag/components/button.tsx',
      'app/javascript/src/tag/components/buttons.tsx',
      'app/javascript/src/tag/components/edit_view.tsx',
      'app/javascript/src/tag/components/rule_row.tsx',
      'app/javascript/src/tag/containers/buttons.ts',
      'app/javascript/src/task/components/checkbox.tsx',
      'app/javascript/src/task/components/delete_button.tsx',
      'app/javascript/src/task/components/done_button.tsx',
      'app/javascript/src/task/components/draggable_task_row.tsx',
      'app/javascript/src/task/components/edit_icon.tsx',
      'app/javascript/src/task/components/edit_title_form.tsx',
      'app/javascript/src/task/components/focus_view.tsx',
      'app/javascript/src/task/components/leaf_list_item.tsx',
      'app/javascript/src/task/components/link.tsx',
      'app/javascript/src/task/components/list_view.tsx',
      'app/javascript/src/task/components/main_buttons.tsx',
      'app/javascript/src/task/components/nested_list.tsx',
      'app/javascript/src/task/components/parent_list_item.tsx',
      'app/javascript/src/task/components/postpone_button.tsx',
      'app/javascript/src/task/components/show_view.tsx',
      'app/javascript/src/task/components/sub_tasks_table.tsx',
      'app/javascript/src/task/components/table_headers.tsx',
      'app/javascript/src/task/components/task_display.tsx',
      'app/javascript/src/task/components/task_row.tsx',
      'app/javascript/src/task/components/task_title.tsx',
      'app/javascript/src/task/components/tree_view.tsx',
      'app/javascript/src/task/containers/parent_task_bread_crumbs.tsx',
      'app/javascript/src/task/selectors.ts',
      'app/javascript/src/timeframe/components/list_view.tsx',
      'app/javascript/src/timeframe/components/section.tsx',
      'app/javascript/src/timeframe/components/task_row.tsx',
    ],
    rules: { '@typescript-eslint/consistent-type-definitions': 'off' as const },
  },

  // Offense count: 69
  {
    files: [
      'app/javascript/helpers/ajax.ts',
      'app/javascript/helpers/debug.ts',
      'app/javascript/helpers/grab.ts',
      'app/javascript/helpers/time_balancer.ts',
      'app/javascript/packs/crash_site_onerror.ts',
      'app/javascript/src/_common/create_basic_reducer.ts',
      'app/javascript/src/_common/create_merged_reducer.ts',
      'app/javascript/src/create_app_store.ts',
      'app/javascript/src/route/action_creators.ts',
      'app/javascript/src/route/helpers.ts',
      'app/javascript/src/route/reducer.ts',
      'app/javascript/src/route/routes.ts',
      'app/javascript/src/tag/action_creators.ts',
      'app/javascript/src/tag/components/edit_view.tsx',
      'app/javascript/src/tag/containers/buttons.ts',
      'app/javascript/src/tag/containers/edit_view.ts',
      'app/javascript/src/tag/reducer.ts',
      'app/javascript/src/tag/selectors.ts',
      'app/javascript/src/task/action_creators.ts',
      'app/javascript/src/task/components/delete_button.tsx',
      'app/javascript/src/task/components/draggable_task_row.tsx',
      'app/javascript/src/task/components/list_view.tsx',
      'app/javascript/src/task/components/main_buttons.tsx',
      'app/javascript/src/task/components/task_display.tsx',
      'app/javascript/src/task/containers/focus_view.ts',
      'app/javascript/src/task/containers/list_view.ts',
      'app/javascript/src/task/containers/parent_task_bread_crumbs.tsx',
      'app/javascript/src/task/containers/show_view.ts',
      'app/javascript/src/task/containers/tree_view.ts',
      'app/javascript/src/task/reducer.ts',
      'app/javascript/src/timeframe/components/task_row.tsx',
      'app/javascript/src/timeframe/utils.ts',
      'spec/javascript/_test_helpers/enzyme_matchers.ts',
      'spec/javascript/task/components/focus_view_spec.tsx',
    ],
    rules: { '@typescript-eslint/explicit-function-return-type': 'off' as const },
  },

  // Offense count: 26
  {
    files: [
      'app/javascript/helpers/ajax.ts',
      'app/javascript/helpers/debug.ts',
      'app/javascript/helpers/grab.ts',
      'app/javascript/helpers/time_balancer.ts',
      'app/javascript/src/_common/create_basic_reducer.ts',
      'app/javascript/src/_common/create_merged_reducer.ts',
      'app/javascript/src/create_app_store.ts',
      'app/javascript/src/route/action_creators.ts',
      'app/javascript/src/route/helpers.ts',
      'app/javascript/src/tag/action_creators.ts',
      'app/javascript/src/tag/components/edit_view.tsx',
      'app/javascript/src/task/action_creators.ts',
      'app/javascript/src/task/components/delete_button.tsx',
      'app/javascript/src/task/components/list_view.tsx',
      'app/javascript/src/task/components/main_buttons.tsx',
      'app/javascript/src/task/components/task_display.tsx',
      'app/javascript/src/timeframe/components/task_row.tsx',
    ],
    rules: { '@typescript-eslint/explicit-module-boundary-types': 'off' as const },
  },

  // Offense count: 11
  {
    files: [
      'app/javascript/helpers/debug.ts',
      'app/javascript/src/route/helpers.ts',
      'app/javascript/src/task/containers/parent_task_bread_crumbs.tsx',
      'app/javascript/src/timeframe/store.ts',
      'app/javascript/src/timeframe/utils.ts',
      'spec/javascript/task/action_creators_spec.tsx',
    ],
    rules: { '@typescript-eslint/init-declarations': 'off' as const },
  },

  // Offense count: 1
  {
    files: ['app/javascript/packs/crash_site_onerror.ts'],
    rules: { '@typescript-eslint/max-params': 'off' as const },
  },

  // Offense count: 5
  {
    files: [
      'app/javascript/@types/timeframe.d.ts',
      'app/javascript/controllers/react_controller.tsx',
      'spec/javascript/_test_helpers/fake_notification.ts',
    ],
    rules: { '@typescript-eslint/member-ordering': 'off' as const },
  },

  // Offense count: 27
  {
    files: [
      'app/javascript/@types/task.d.ts',
      'app/javascript/@types/timeframe.d.ts',
      'spec/javascript/_test_helpers/vitest.d.ts',
    ],
    rules: { '@typescript-eslint/method-signature-style': 'off' as const },
  },

  // Offense count: 1
  {
    files: ['app/javascript/packs/crash_site_onerror.ts'],
    rules: { '@typescript-eslint/no-base-to-string': 'off' as const },
  },

  // Offense count: 22
  {
    files: [
      'app/javascript/src/_common/create_basic_reducer.ts',
      'app/javascript/src/task/components/postpone_button.tsx',
      'app/javascript/src/timeframe/store.ts',
      'spec/javascript/route/reducer_spec.ts',
      'spec/javascript/tag/reducer_spec.ts',
      'spec/javascript/task/action_creators_spec.tsx',
      'spec/javascript/task/reducer_spec.tsx',
      'spec/javascript/timeframe/store_spec.ts',
    ],
    rules: { '@typescript-eslint/no-confusing-void-expression': 'off' as const },
  },

  // Offense count: 5
  {
    files: [
      'app/javascript/controllers/react_controller.tsx',
      'app/javascript/src/create_app_store.ts',
      'app/javascript/src/task/components/edit_title_form.tsx',
      'spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx',
      'spec/javascript/task/containers/show_view_spec.tsx',
    ],
    rules: { '@typescript-eslint/no-deprecated': 'off' as const },
  },

  // Offense count: 2
  {
    files: ['spec/javascript/_test_helpers/vitest.d.ts'],
    rules: { '@typescript-eslint/no-empty-object-type': 'off' as const },
  },

  // Offense count: 14
  {
    files: [
      'app/javascript/@types/globals.d.ts',
      'app/javascript/helpers/debug.ts',
      'app/javascript/helpers/request.ts',
      'app/javascript/src/_common/create_merged_reducer.ts',
      'app/javascript/src/task/components/list_view.tsx',
      'spec/javascript/_test_helpers/factories/state.ts',
      'spec/javascript/_test_helpers/shims.ts',
      'spec/javascript/helpers/debug_spec.ts',
      'spec/javascript/test_helper.ts',
    ],
    rules: { '@typescript-eslint/no-explicit-any': 'off' as const },
  },

  // Offense count: 3
  {
    files: [
      'app/javascript/helpers/request.ts',
      'app/javascript/src/timeframe/components/list_view.tsx',
    ],
    rules: { '@typescript-eslint/no-floating-promises': 'off' as const },
  },

  // Offense count: 3
  {
    files: ['app/javascript/src/task/action_creators.ts'],
    rules: { '@typescript-eslint/no-misused-promises': 'off' as const },
  },

  // Offense count: 1
  {
    files: ['app/javascript/src/_common/create_merged_reducer.ts'],
    rules: { '@typescript-eslint/no-redundant-type-constituents': 'off' as const },
  },

  // Offense count: 2
  {
    files: ['app/javascript/src/application.tsx'],
    rules: { '@typescript-eslint/no-require-imports': 'off' as const },
  },

  // Offense count: 14
  {
    files: [
      'app/javascript/helpers/authenticity_token.ts',
      'app/javascript/src/tag/containers/buttons.ts',
      'app/javascript/src/task/bulk_store.ts',
      'app/javascript/src/task/components/draggable_task_row.tsx',
      'app/javascript/src/task/components/list_view.tsx',
      'app/javascript/src/task/components/task_display.tsx',
      'app/javascript/src/task/selectors.ts',
      'app/javascript/src/task/store.ts',
    ],
    rules: { '@typescript-eslint/no-unnecessary-condition': 'off' as const },
  },

  // Offense count: 2
  {
    files: [
      'app/javascript/helpers/debug.ts',
      'app/javascript/src/_common/create_basic_reducer.ts',
    ],
    rules: { '@typescript-eslint/no-unnecessary-type-parameters': 'off' as const },
  },

  // Offense count: 7
  {
    files: [
      'app/javascript/src/_common/create_merged_reducer.ts',
      'app/javascript/src/task/action_creators.ts',
      'app/javascript/src/task/components/list_view.tsx',
    ],
    rules: { '@typescript-eslint/no-unsafe-argument': 'off' as const },
  },

  // Offense count: 14
  {
    files: [
      'app/javascript/helpers/debug.ts',
      'app/javascript/src/_common/create_merged_reducer.ts',
      'app/javascript/src/task/action_creators.ts',
      'app/javascript/src/task/components/list_view.tsx',
      'spec/javascript/_test_helpers/factories/state.ts',
      'spec/javascript/task/action_creators_spec.tsx',
    ],
    rules: { '@typescript-eslint/no-unsafe-assignment': 'off' as const },
  },

  // Offense count: 4
  {
    files: [
      'app/javascript/src/task/components/list_view.tsx',
      'spec/javascript/task/action_creators_spec.tsx',
      'spec/javascript/timeframe/store_spec.ts',
    ],
    rules: { '@typescript-eslint/no-unsafe-call': 'off' as const },
  },

  // Offense count: 12
  {
    files: [
      'app/javascript/helpers/debug.ts',
      'app/javascript/src/_common/create_merged_reducer.ts',
      'app/javascript/src/task/components/list_view.tsx',
      'spec/javascript/_test_helpers/shims.ts',
      'spec/javascript/helpers/debug_spec.ts',
      'spec/javascript/task/action_creators_spec.tsx',
      'spec/javascript/test_helper.ts',
      'spec/javascript/timeframe/store_spec.ts',
    ],
    rules: { '@typescript-eslint/no-unsafe-member-access': 'off' as const },
  },

  // Offense count: 3
  {
    files: [
      'app/javascript/helpers/debug.ts',
      'app/javascript/src/_common/create_merged_reducer.ts',
    ],
    rules: { '@typescript-eslint/no-unsafe-return': 'off' as const },
  },

  // Offense count: 32
  {
    files: [
      'app/javascript/helpers/debug.ts',
      'spec/javascript/_test_helpers/enzyme_matchers.ts',
      'spec/javascript/_test_helpers/shims.ts',
      'spec/javascript/helpers/debug_spec.ts',
      'spec/javascript/task/action_creators_spec.tsx',
      'spec/javascript/task/components/leaf_list_item_spec.tsx',
      'spec/javascript/task/components/list_view_spec.tsx',
      'spec/javascript/test_helper.ts',
      'spec/javascript/timeframe/components/list_view_spec.tsx',
      'spec/javascript/timeframe/store_spec.ts',
    ],
    rules: { '@typescript-eslint/no-unsafe-type-assertion': 'off' as const },
  },

  // Offense count: 2
  {
    files: ['spec/javascript/_test_helpers/vitest.d.ts'],
    rules: { '@typescript-eslint/no-unused-vars': 'off' as const },
  },

  // Offense count: 2
  {
    files: ['app/javascript/packs/crash_site_onerror.ts'],
    rules: { '@typescript-eslint/no-use-before-define': 'off' as const },
  },

  // Offense count: 6
  {
    files: [
      'app/javascript/src/_common/create_merged_reducer.ts',
      'spec/javascript/task/action_creators_spec.tsx',
      'spec/javascript/timeframe/store_spec.ts',
    ],
    rules: { '@typescript-eslint/prefer-destructuring': 'off' as const },
  },

  // Offense count: 1
  {
    files: ['app/javascript/@types/globals.d.ts'],
    rules: { '@typescript-eslint/prefer-function-type': 'off' as const },
  },

  // Offense count: 8
  {
    files: [
      'app/javascript/src/task/components/task_row.tsx',
      'app/javascript/src/task/reducer.ts',
      'app/javascript/src/task/store.ts',
      'app/javascript/src/timeframe/components/task_row.tsx',
      'spec/javascript/_test_helpers/factories/state.ts',
      'spec/javascript/_test_helpers/factories/task.ts',
    ],
    rules: { '@typescript-eslint/prefer-nullish-coalescing': 'off' as const },
  },

  // Offense count: 4
  {
    files: [
      'app/javascript/helpers/authenticity_token.ts',
      'app/javascript/packs/crash_site_onerror.ts',
      'app/javascript/src/tag/components/edit_view.tsx',
      'app/javascript/src/tag/reducer.ts',
    ],
    rules: { '@typescript-eslint/prefer-optional-chain': 'off' as const },
  },

  // Offense count: 8
  {
    files: [
      'app/javascript/helpers/ajax.ts',
      'app/javascript/src/timeframe/store.ts',
      'spec/javascript/_test_helpers/fake_notification.ts',
    ],
    rules: { '@typescript-eslint/promise-function-async': 'off' as const },
  },

  // Offense count: 1
  {
    files: ['app/javascript/packs/crash_site_onerror.ts'],
    rules: { '@typescript-eslint/restrict-template-expressions': 'off' as const },
  },

  // Offense count: 39
  {
    files: [
      'app/javascript/helpers/authenticity_token.ts',
      'app/javascript/helpers/debug.ts',
      'app/javascript/packs/crash_site_onerror.ts',
      'app/javascript/src/tag/components/buttons.tsx',
      'app/javascript/src/tag/containers/buttons.ts',
      'app/javascript/src/task/action_creators.ts',
      'app/javascript/src/task/bulk_store.ts',
      'app/javascript/src/task/components/checkbox.tsx',
      'app/javascript/src/task/components/draggable_task_row.tsx',
      'app/javascript/src/task/components/list_view.tsx',
      'app/javascript/src/task/components/show_view.tsx',
      'app/javascript/src/task/components/task_display.tsx',
      'app/javascript/src/task/components/task_row.tsx',
      'app/javascript/src/task/components/task_title.tsx',
      'app/javascript/src/task/reducer.ts',
      'app/javascript/src/task/selectors.ts',
      'app/javascript/src/task/store.ts',
      'app/javascript/src/timeframe/components/task_row.tsx',
      'spec/javascript/_test_helpers/factories/task.ts',
    ],
    rules: { '@typescript-eslint/strict-boolean-expressions': 'off' as const },
  },

  // Offense count: 45
  {
    files: [
      'app/javascript/src/application.tsx',
      'app/javascript/src/globals.ts',
      'app/javascript/src/tag/action_creators.ts',
      'app/javascript/src/task/action_creators.ts',
      'spec/javascript/_test_helpers/fake_notification.ts',
      'spec/javascript/app_store_spec.ts',
      'spec/javascript/controllers/hotkeys_controller_spec.ts',
      'spec/javascript/task/action_creators_spec.tsx',
      'spec/javascript/task/components/checkbox_spec.tsx',
      'spec/javascript/task/components/focus_view_spec.tsx',
      'spec/javascript/task/components/list_view_spec.tsx',
      'spec/javascript/task/components/nested_list_spec.tsx',
      'spec/javascript/task/components/parent_list_item_spec.tsx',
      'spec/javascript/task/components/postpone_button_spec.tsx',
      'spec/javascript/task/components/show_view_spec.tsx',
      'spec/javascript/task/components/sub_tasks_table_spec.tsx',
      'spec/javascript/task/components/task_row_spec.tsx',
      'spec/javascript/timeframe/components/task_row_spec.tsx',
      'spec/javascript/timeframe/store_spec.ts',
    ],
    rules: { '@typescript-eslint/strict-void-return': 'off' as const },
  },

  // Offense count: 46
  {
    files: [
      'app/javascript/src/tag/components/buttons.tsx',
      'app/javascript/src/tag/components/edit_view.tsx',
      'app/javascript/src/tag/components/rule_row.tsx',
      'app/javascript/src/task/components/delete_button.tsx',
      'app/javascript/src/task/components/done_button.tsx',
      'app/javascript/src/task/components/draggable_task_row.tsx',
      'app/javascript/src/task/components/edit_title_form.tsx',
      'app/javascript/src/task/components/focus_view.tsx',
      'app/javascript/src/task/components/leaf_list_item.tsx',
      'app/javascript/src/task/components/list_view.tsx',
      'app/javascript/src/task/components/nested_list.tsx',
      'app/javascript/src/task/components/postpone_button.tsx',
      'app/javascript/src/task/components/task_row.tsx',
      'app/javascript/src/timeframe/components/list_view.tsx',
      'app/javascript/src/timeframe/components/section.tsx',
      'app/javascript/src/timeframe/components/task_row.tsx',
      'spec/javascript/task/action_creators_spec.tsx',
      'spec/javascript/task/components/leaf_list_item_spec.tsx',
      'spec/javascript/task/components/list_view_spec.tsx',
    ],
    rules: { '@typescript-eslint/unbound-method': 'off' as const },
  },

  // Offense count: 1
  {
    files: ['spec/javascript/_test_helpers/vitest.d.ts'],
    rules: { '@typescript-eslint/unified-signatures': 'off' as const },
  },

  // Offense count: 60
  {
    files: [
      'app/javascript/helpers/ajax.ts',
      'app/javascript/helpers/to_english.ts',
      'app/javascript/src/application.tsx',
      'app/javascript/src/route/helpers.ts',
      'app/javascript/src/tag/action_creators.ts',
      'app/javascript/src/tag/components/edit_view.tsx',
      'app/javascript/src/tag/components/rule_row.tsx',
      'app/javascript/src/tag/selectors.ts',
      'app/javascript/src/task/components/list_view.tsx',
      'app/javascript/src/task/components/postpone_button.tsx',
      'app/javascript/src/task/components/sub_tasks_table.tsx',
      'app/javascript/src/task/selectors.ts',
      'app/javascript/src/task/store.ts',
      'app/javascript/src/timeframe/store.ts',
      'spec/javascript/_test_helpers/enzyme_matchers.ts',
      'spec/javascript/helpers/grab_spec.ts',
      'spec/javascript/tag/action_creators_spec.ts',
      'spec/javascript/task/action_creators_spec.tsx',
      'spec/javascript/task/components/focus_view_spec.tsx',
      'spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx',
      'spec/javascript/task/containers/show_view_spec.tsx',
      'spec/javascript/timeframe/store_spec.ts',
    ],
    rules: { 'arrow-body-style': 'off' as const },
  },

  // Offense count: 3
  {
    files: [
      'app/javascript/src/tag/components/edit_view.tsx',
      'app/javascript/src/task/components/edit_title_form.tsx',
      'app/javascript/src/task/components/list_view.tsx',
    ],
    rules: { 'camelcase': 'off' as const },
  },

  // Offense count: 24
  {
    files: [
      'app/javascript/@types/globals.d.ts',
      'app/javascript/channels/consumer.js',
      'app/javascript/controllers/dialog_controller.ts',
      'app/javascript/helpers/authenticity_token.ts',
      'app/javascript/src/application.tsx',
      'app/javascript/src/tag/components/rule_row.tsx',
      'app/javascript/src/task/components/list_view.tsx',
      'app/javascript/src/task/components/task_row.tsx',
      'app/javascript/src/task/containers/parent_task_bread_crumbs.tsx',
      'app/javascript/src/timeframe/components/task_row.tsx',
      'spec/javascript/_test_helpers/fake_notification.ts',
      'spec/javascript/helpers/debug_spec.ts',
      'spec/javascript/test_helper.ts',
    ],
    rules: { 'capitalized-comments': 'off' as const },
  },

  // Offense count: 3
  {
    files: [
      'app/javascript/src/application.tsx',
      'app/javascript/src/globals.ts',
    ],
    rules: { 'id-length': 'off' as const },
  },

  // Offense count: 1
  {
    files: ['spec/javascript/packs/application_spec.ts'],
    rules: { 'import/no-unresolved': 'off' as const },
  },

  // Offense count: 3
  {
    files: ['spec/javascript/_test_helpers/enzyme_matchers.ts'],
    rules: { 'max-len': 'off' as const },
  },

  // Offense count: 7
  {
    files: [
      'spec/javascript/helpers/time_balancer_spec.ts',
      'spec/javascript/tag/selectors_spec.ts',
      'spec/javascript/task/action_creators_spec.tsx',
      'spec/javascript/task/components/list_view_spec.tsx',
      'spec/javascript/timeframe/store_spec.ts',
    ],
    rules: { 'max-lines-per-function': 'off' as const },
  },

  // Offense count: 10
  {
    files: [
      'app/javascript/helpers/debug.ts',
      'app/javascript/helpers/time_balancer.ts',
      'app/javascript/src/task/components/list_view.tsx',
      'app/javascript/src/timeframe/utils.ts',
      'spec/javascript/tag/selectors_spec.ts',
      'spec/javascript/task/components/list_view_spec.tsx',
      'spec/javascript/timeframe/store_spec.ts',
    ],
    rules: { 'max-statements': 'off' as const },
  },

  // Offense count: 4
  {
    files: [
      'spec/javascript/_test_helpers/fake_notification.ts',
      'spec/javascript/helpers/debug_spec.ts',
      'spec/javascript/test_helper.ts',
    ],
    rules: { 'no-inline-comments': 'off' as const },
  },

  // Offense count: 3
  {
    files: [
      'app/javascript/helpers/grab.ts',
      'app/javascript/src/tag/reducer.ts',
      'spec/javascript/_test_helpers/factories/task.ts',
    ],
    rules: { 'no-prototype-builtins': 'off' as const },
  },

  // Offense count: 29
  {
    files: [
      'app/javascript/helpers/debug.ts',
      'app/javascript/helpers/to_english.ts',
      'app/javascript/src/tag/components/button.tsx',
      'app/javascript/src/tag/components/rule_row.tsx',
      'app/javascript/src/tag/selectors.ts',
      'app/javascript/src/task/components/done_button.tsx',
      'app/javascript/src/task/components/postpone_button.tsx',
      'app/javascript/src/task/components/task_row.tsx',
      'app/javascript/src/timeframe/components/section.tsx',
      'app/javascript/src/timeframe/components/task_row.tsx',
      'app/javascript/src/timeframe/utils.ts',
      'spec/javascript/_test_helpers/enzyme_matchers.ts',
    ],
    rules: { 'no-ternary': 'off' as const },
  },

  // Offense count: 1
  {
    files: ['app/javascript/helpers/request.ts'],
    rules: { 'no-void': 'off' as const },
  },

  // Offense count: 17
  {
    files: [
      'app/javascript/src/route/routes.ts',
      'app/javascript/src/tag/components/edit_view.tsx',
      'app/javascript/src/tag/selectors.ts',
      'app/javascript/src/task/action_creators.ts',
      'app/javascript/src/task/components/draggable_task_row.tsx',
      'app/javascript/src/task/components/task_row.tsx',
      'app/javascript/src/task/containers/list_view.ts',
      'app/javascript/src/task/reducer.ts',
      'app/javascript/src/timeframe/components/list_view.tsx',
      'app/javascript/src/timeframe/utils.ts',
      'spec/javascript/_test_helpers/enzyme_matchers.ts',
      'spec/javascript/route/action_creators_spec.ts',
      'spec/javascript/tag/action_creators_spec.ts',
      'spec/javascript/task/action_creators_spec.tsx',
      'spec/javascript/task/reducer_spec.tsx',
      'spec/javascript/task/selectors_spec.tsx',
    ],
    rules: { 'sort-imports': 'off' as const },
  },

  // Offense count: 193
  {
    files: [
      'app/javascript/helpers/ajax.ts',
      'app/javascript/helpers/debug.ts',
      'app/javascript/helpers/request.ts',
      'app/javascript/helpers/time_balancer.ts',
      'app/javascript/src/route/action_creators.ts',
      'app/javascript/src/tag/action_creators.ts',
      'app/javascript/src/tag/components/button.tsx',
      'app/javascript/src/tag/components/edit_view.tsx',
      'app/javascript/src/tag/selectors.ts',
      'app/javascript/src/task/action_creators.ts',
      'app/javascript/src/task/bulk_store.ts',
      'app/javascript/src/task/components/delete_button.tsx',
      'app/javascript/src/task/components/edit_title_form.tsx',
      'app/javascript/src/task/components/postpone_button.tsx',
      'app/javascript/src/task/components/sub_tasks_table.tsx',
      'app/javascript/src/task/containers/focus_view.ts',
      'app/javascript/src/task/containers/list_view.ts',
      'app/javascript/src/task/reducer.ts',
      'app/javascript/src/task/selectors.ts',
      'app/javascript/src/task/store.ts',
      'app/javascript/src/timeframe/components/list_view.tsx',
      'app/javascript/src/timeframe/name_map.ts',
      'app/javascript/src/timeframe/store.ts',
      'app/javascript/src/timeframe/utils.ts',
      'spec/javascript/_test_helpers/enzyme_matchers.ts',
      'spec/javascript/_test_helpers/factories/state.ts',
      'spec/javascript/_test_helpers/factories/tag.ts',
      'spec/javascript/_test_helpers/factories/task.ts',
      'spec/javascript/_test_helpers/factories/timeframe.ts',
      'spec/javascript/app_reducer_spec.ts',
      'spec/javascript/app_store_spec.ts',
      'spec/javascript/helpers/time_balancer_spec.ts',
      'spec/javascript/route/action_creators_spec.ts',
      'spec/javascript/route/reducer_spec.ts',
      'spec/javascript/tag/action_creators_spec.ts',
      'spec/javascript/tag/components/button_spec.tsx',
      'spec/javascript/tag/components/buttons_spec.tsx',
      'spec/javascript/tag/components/edit_view_spec.tsx',
      'spec/javascript/tag/components/rule_row_spec.tsx',
      'spec/javascript/tag/reducer_spec.ts',
      'spec/javascript/tag/selectors_spec.ts',
      'spec/javascript/task/action_creators_spec.tsx',
      'spec/javascript/task/components/show_view_spec.tsx',
      'spec/javascript/task/components/sub_tasks_table_spec.tsx',
      'spec/javascript/task/components/task_row_spec.tsx',
      'spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx',
      'spec/javascript/task/reducer_spec.tsx',
      'spec/javascript/task/selectors_spec.tsx',
      'spec/javascript/timeframe/components/list_view_spec.tsx',
      'spec/javascript/timeframe/components/task_row_spec.tsx',
      'spec/javascript/timeframe/store_spec.ts',
      'vitest.config.ts',
    ],
    rules: { 'sort-keys': 'off' as const },
  },

  // Offense count: 193
  {
    files: [
      'app/javascript/helpers/ajax.ts',
      'app/javascript/helpers/debug.ts',
      'app/javascript/helpers/request.ts',
      'app/javascript/helpers/time_balancer.ts',
      'app/javascript/src/route/action_creators.ts',
      'app/javascript/src/tag/action_creators.ts',
      'app/javascript/src/tag/components/button.tsx',
      'app/javascript/src/tag/components/edit_view.tsx',
      'app/javascript/src/tag/selectors.ts',
      'app/javascript/src/task/action_creators.ts',
      'app/javascript/src/task/bulk_store.ts',
      'app/javascript/src/task/components/delete_button.tsx',
      'app/javascript/src/task/components/edit_title_form.tsx',
      'app/javascript/src/task/components/postpone_button.tsx',
      'app/javascript/src/task/components/sub_tasks_table.tsx',
      'app/javascript/src/task/containers/focus_view.ts',
      'app/javascript/src/task/containers/list_view.ts',
      'app/javascript/src/task/reducer.ts',
      'app/javascript/src/task/selectors.ts',
      'app/javascript/src/task/store.ts',
      'app/javascript/src/timeframe/components/list_view.tsx',
      'app/javascript/src/timeframe/name_map.ts',
      'app/javascript/src/timeframe/store.ts',
      'app/javascript/src/timeframe/utils.ts',
      'spec/javascript/_test_helpers/enzyme_matchers.ts',
      'spec/javascript/_test_helpers/factories/state.ts',
      'spec/javascript/_test_helpers/factories/tag.ts',
      'spec/javascript/_test_helpers/factories/task.ts',
      'spec/javascript/_test_helpers/factories/timeframe.ts',
      'spec/javascript/app_reducer_spec.ts',
      'spec/javascript/app_store_spec.ts',
      'spec/javascript/helpers/time_balancer_spec.ts',
      'spec/javascript/route/action_creators_spec.ts',
      'spec/javascript/route/reducer_spec.ts',
      'spec/javascript/tag/action_creators_spec.ts',
      'spec/javascript/tag/components/button_spec.tsx',
      'spec/javascript/tag/components/buttons_spec.tsx',
      'spec/javascript/tag/components/edit_view_spec.tsx',
      'spec/javascript/tag/components/rule_row_spec.tsx',
      'spec/javascript/tag/reducer_spec.ts',
      'spec/javascript/tag/selectors_spec.ts',
      'spec/javascript/task/action_creators_spec.tsx',
      'spec/javascript/task/components/show_view_spec.tsx',
      'spec/javascript/task/components/sub_tasks_table_spec.tsx',
      'spec/javascript/task/components/task_row_spec.tsx',
      'spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx',
      'spec/javascript/task/reducer_spec.tsx',
      'spec/javascript/task/selectors_spec.tsx',
      'spec/javascript/timeframe/components/list_view_spec.tsx',
      'spec/javascript/timeframe/components/task_row_spec.tsx',
      'spec/javascript/timeframe/store_spec.ts',
      'vitest.config.ts',
    ],
    rules: { 'sort-keys-fix/sort-keys-fix': 'off' as const },
  },

  // Offense count: 13
  {
    files: [
      'spec/javascript/tag/selectors_spec.ts',
      'spec/javascript/task/components/list_view_spec.tsx',
      'spec/javascript/timeframe/store_spec.ts',
    ],
    rules: { 'vitest/max-expects': 'off' as const },
  },

  // Offense count: 7
  {
    files: [
      'spec/javascript/helpers/debug_spec.ts',
      'spec/javascript/route/action_creators_spec.ts',
      'spec/javascript/task/action_creators_spec.tsx',
    ],
    rules: { 'vitest/no-hooks': 'off' as const },
  },

  // Offense count: 1
  {
    files: ['spec/javascript/task/action_creators_spec.tsx'],
    rules: { 'vitest/no-standalone-expect': 'off' as const },
  },

  // Offense count: 11
  {
    files: [
      'spec/javascript/app_store_spec.ts',
      'spec/javascript/task/action_creators_spec.tsx',
      'spec/javascript/task/components/checkbox_spec.tsx',
      'spec/javascript/task/components/edit_title_form_spec.tsx',
      'spec/javascript/timeframe/store_spec.ts',
    ],
    rules: { 'vitest/prefer-called-with': 'off' as const },
  },

  // Offense count: 4
  {
    files: [
      'spec/javascript/helpers/time_balancer_spec.ts',
      'spec/javascript/helpers/to_english_spec.ts',
      'spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx',
    ],
    rules: { 'vitest/prefer-lowercase-title': 'off' as const },
  },

  // Offense count: 4
  {
    files: ['spec/javascript/task/action_creators_spec.tsx'],
    rules: { 'vitest/prefer-mock-promise-shorthand': 'off' as const },
  },

  // Offense count: 68
  {
    files: [
      'spec/javascript/app_reducer_spec.ts',
      'spec/javascript/app_store_spec.ts',
      'spec/javascript/helpers/time_balancer_spec.ts',
      'spec/javascript/route/action_creators_spec.ts',
      'spec/javascript/route/helpers_spec.ts',
      'spec/javascript/route/reducer_spec.ts',
      'spec/javascript/tag/action_creators_spec.ts',
      'spec/javascript/tag/reducer_spec.ts',
      'spec/javascript/tag/selectors_spec.ts',
      'spec/javascript/task/action_creators_spec.tsx',
      'spec/javascript/task/reducer_spec.tsx',
      'spec/javascript/task/selectors_spec.tsx',
      'spec/javascript/timeframe/store_spec.ts',
    ],
    rules: { 'vitest/prefer-strict-equal': 'off' as const },
  },

  // Offense count: 1
  {
    files: ['spec/javascript/packs/application_spec.ts'],
    rules: { 'vitest/prefer-to-be': 'off' as const },
  },

  // Offense count: 8
  {
    files: [
      'app/javascript/src/application.tsx',
      'spec/javascript/_test_helpers/factories/id.ts',
      'spec/javascript/test_helper.ts',
      'spec/support/disable_animations.js',
    ],
    rules: { 'vitest/require-hook': 'off' as const },
  },
];
