root: true
# have to include `plugin:react/recommended` to avoid errors
extends: ['eslint:all', 'plugin:react/recommended']
plugins: [react]
parserOptions:
  sourceType: module
env:
  browser: true
  es6: true
  node: true
globals:
  $: true
ecmaFeatures:
  jsx: true
rules:
  # to enable someday
  capitalized-comments: off
  max-len: [error, 110]
  max-statements: [error, { max: 14 }]
  multiline-ternary: off
  # no-console: off
  no-mixed-operators: off
  prefer-destructuring: off
  react/forbid-prop-types: off
  react/no-find-dom-node: off
  react/no-multi-comp: off
  react/no-set-state: off
  react/no-string-refs: off
  react/prefer-es6-class: off
  react/prefer-stateless-function: off
  sort-keys: off
  sort-imports: off
  camelcase: off
  strict: off # need to switch module syntax
  # departures from default
  brace-style: [error, 1tbs, { allowSingleLine: true }]
  func-style: [error, declaration]
  id-length: [error, { exceptions: [_, $] }]
  indent: [error, 2]
  jsx-quotes: [error, prefer-single]
  max-statements-per-line: [error, { max: 2 }]
  no-underscore-dangle: [error, { allowAfterThis: true }]
  object-property-newline: [error, { allowMultiplePropertiesPerLine: true }]
  one-var: [error, never]
  padded-blocks: [error, never]
  prefer-arrow-callback: [error, { allowNamedFunctions: true }]
  quote-props: [error, as-needed, { keywords: true }]
  quotes: [error, single]
  space-before-function-paren: [error, { anonymous: always, named: never }]
  spaced-comment: [error, always, { markers: [=] }]
  react/jsx-indent: [error, 2]
  react/jsx-indent-props: [error, 2]
  react/jsx-wrap-multilines: [error, { declaration: false }]
  # disabled
  init-declarations: off
  no-inline-comments: off
  no-magic-numbers: off
  no-ternary: off
  prefer-reflect: off
  require-jsdoc: off
  react/jsx-handler-names: off
  react/jsx-max-props-per-line: off
  react/jsx-sort-props: off
