// This configuration was generated by `exe/eslint_autogen`
// on 2026-02-20 03:36:05 UTC.
// The point is for the user to remove these configuration records
// one by one as the offenses are removed from the code base.

import type {Linter} from "eslint";

const config: Linter.Config[] = [
  // Offense count: 35
  {
    files: [
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/helpers/ajax.ts",
      "app/javascript/helpers/request.ts",
      "app/javascript/helpers/to_english.ts",
      "app/javascript/route/helpers.ts",
      "app/javascript/route/routes.ts",
      "app/javascript/tag/action_creators.ts",
      "app/javascript/tag/components/edit_view.tsx",
      "app/javascript/tag/components/rule_row.tsx",
      "app/javascript/tag/selectors.ts",
      "app/javascript/task/bulk_store.ts",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/sub_tasks_table.tsx",
      "app/javascript/task/selectors.ts",
      "app/javascript/task/store.ts",
      "app/javascript/timeframe/store.ts",
      "spec/javascript/timeframe/store_spec.ts",
    ],
    rules: {
      "@stylistic/arrow-parens": "off",
    },
  },
  // Offense count: 22
  {
    files: [
      "app/javascript/helpers/debug.ts",
      "app/javascript/tag/selectors.ts",
      "app/javascript/task/components/sub_tasks_table.tsx",
      "spec/javascript/_test_helpers/factories/task.ts",
      "spec/javascript/tag/containers/edit_view_spec.tsx",
      "spec/javascript/task/containers/focus_view_spec.tsx",
      "spec/javascript/task/containers/list_view_spec.tsx",
      "spec/javascript/task/containers/show_view_spec.tsx",
      "spec/javascript/task/containers/tree_view_spec.tsx",
      "spec/javascript/timeframe/containers/list_view_spec.tsx",
      "spec/javascript/timeframe/store_spec.ts",
    ],
    rules: {
      "@stylistic/function-paren-newline": "off",
    },
  },
  // Offense count: 5
  {
    files: [
      "app/javascript/task/store.ts",
    ],
    rules: {
      "@stylistic/indent": "off",
    },
  },
  // Offense count: 11
  {
    files: [
      "app/javascript/@types/state.d.ts",
      "app/javascript/@types/timeframe.d.ts",
    ],
    rules: {
      "@stylistic/indent-binary-ops": "off",
    },
  },
  // Offense count: 2
  {
    files: [
      "vitest.config.ts",
    ],
    rules: {
      "@stylistic/max-len": "off",
    },
  },
  // Offense count: 82
  {
    files: [
      "app/javascript/helpers/debug.ts",
      "app/javascript/tag/components/button.tsx",
      "app/javascript/tag/components/buttons.tsx",
      "app/javascript/tag/components/edit_view.tsx",
      "app/javascript/tag/components/rule_row.tsx",
      "app/javascript/task/components/checkbox.tsx",
      "app/javascript/task/components/delete_button.tsx",
      "app/javascript/task/components/done_button.tsx",
      "app/javascript/task/components/draggable_task_row.tsx",
      "app/javascript/task/components/edit_title_form.tsx",
      "app/javascript/task/components/focus_view.tsx",
      "app/javascript/task/components/leaf_list_item.tsx",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/components/main_buttons.tsx",
      "app/javascript/task/components/nested_list.tsx",
      "app/javascript/task/components/parent_list_item.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/show_view.tsx",
      "app/javascript/task/components/sub_tasks_table.tsx",
      "app/javascript/task/components/task_row.tsx",
      "app/javascript/task/components/task_title.tsx",
      "app/javascript/task/components/tree_view.tsx",
      "app/javascript/timeframe/components/list_view.tsx",
      "app/javascript/timeframe/components/section.tsx",
      "app/javascript/timeframe/components/task_row.tsx",
      "spec/javascript/_test_helpers/factories/task.ts",
    ],
    rules: {
      "@stylistic/member-delimiter-style": "off",
    },
  },
  // Offense count: 7
  {
    files: [
      "app/javascript/@types/globals.d.ts",
      "app/javascript/controllers/index.ts",
      "app/javascript/helpers/authenticity_token.ts",
      "app/javascript/tag/components/rule_row.tsx",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/containers/parent_task_bread_crumbs.tsx",
    ],
    rules: {
      "@stylistic/multiline-comment-style": "off",
    },
  },
  // Offense count: 38
  {
    files: [
      "app/javascript/helpers/debug.ts",
      "app/javascript/helpers/to_english.ts",
      "app/javascript/tag/components/button.tsx",
      "app/javascript/tag/components/rule_row.tsx",
      "app/javascript/tag/selectors.ts",
      "app/javascript/task/components/done_button.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/task_row.tsx",
      "app/javascript/timeframe/components/section.tsx",
      "app/javascript/timeframe/components/task_row.tsx",
      "app/javascript/timeframe/utils.ts",
    ],
    rules: {
      "@stylistic/multiline-ternary": "off",
    },
  },
  // Offense count: 5
  {
    files: [
      "app/javascript/helpers/authenticity_token.ts",
      "app/javascript/tag/components/rule_row.tsx",
      "app/javascript/task/components/sub_tasks_table.tsx",
      "app/javascript/timeframe/components/table_headers.tsx",
    ],
    rules: {
      "@stylistic/no-extra-parens": "off",
    },
  },
  // Offense count: 6
  {
    files: [
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/application.tsx",
      "app/javascript/crash_site_onerror.ts",
      "app/javascript/helpers/debug.ts",
    ],
    rules: {
      "@stylistic/no-trailing-spaces": "off",
    },
  },
  // Offense count: 16
  {
    files: [
      "app/javascript/@types/globals.d.ts",
      "app/javascript/helpers/grab.ts",
      "app/javascript/route/routes.ts",
      "app/javascript/tag/components/rule_row.tsx",
      "app/javascript/task/components/sub_tasks_table.tsx",
    ],
    rules: {
      "@stylistic/object-curly-spacing": "off",
    },
  },
  // Offense count: 11
  {
    files: [
      "app/javascript/@types/state.d.ts",
      "app/javascript/@types/timeframe.d.ts",
    ],
    rules: {
      "@stylistic/operator-linebreak": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/helpers/debug.ts",
    ],
    rules: {
      "@stylistic/padded-blocks": "off",
    },
  },
  // Offense count: 7
  {
    files: [
      "app/javascript/@types/state.d.ts",
      "app/javascript/@types/tag.d.ts",
      "app/javascript/@types/task.d.ts",
      "app/javascript/@types/turbo.d.ts",
      "app/javascript/task/components/edit_title_form.tsx",
    ],
    rules: {
      "@stylistic/semi": "off",
    },
  },
  // Offense count: 4
  {
    files: [
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/await-thenable": "off",
    },
  },
  // Offense count: 6
  {
    files: [
      "app/javascript/tag/components/rule_row.tsx",
      "app/javascript/task/components/focus_view.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "spec/javascript/_test_helpers/fake_notification.ts",
    ],
    rules: {
      "@typescript-eslint/class-methods-use-this": "off",
    },
  },
  // Offense count: 22
  {
    files: [
      "app/javascript/helpers/debug.ts",
      "spec/javascript/_test_helpers/shims.ts",
      "spec/javascript/helpers/debug_spec.ts",
      "spec/javascript/setup.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/timeframe/components/list_view_spec.tsx",
      "spec/javascript/timeframe/store_spec.ts",
    ],
    rules: {
      "@typescript-eslint/consistent-type-assertions": "off",
    },
  },
  // Offense count: 81
  {
    files: [
      "app/javascript/@types/globals.d.ts",
      "app/javascript/@types/route.d.ts",
      "app/javascript/@types/state.d.ts",
      "app/javascript/@types/tag.d.ts",
      "app/javascript/@types/task.d.ts",
      "app/javascript/@types/timeframe.d.ts",
      "app/javascript/@types/turbo.d.ts",
      "app/javascript/@types/user.d.ts",
      "app/javascript/_common/create_basic_reducer.ts",
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/helpers/request.ts",
      "app/javascript/route/action_creators.ts",
      "app/javascript/route/reducer.ts",
      "app/javascript/route/routes.ts",
      "app/javascript/tag/components/button.tsx",
      "app/javascript/tag/components/buttons.tsx",
      "app/javascript/tag/components/edit_view.tsx",
      "app/javascript/tag/components/rule_row.tsx",
      "app/javascript/tag/containers/buttons.ts",
      "app/javascript/task/components/checkbox.tsx",
      "app/javascript/task/components/delete_button.tsx",
      "app/javascript/task/components/done_button.tsx",
      "app/javascript/task/components/draggable_task_row.tsx",
      "app/javascript/task/components/edit_icon.tsx",
      "app/javascript/task/components/edit_title_form.tsx",
      "app/javascript/task/components/focus_view.tsx",
      "app/javascript/task/components/leaf_list_item.tsx",
      "app/javascript/task/components/link.tsx",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/components/main_buttons.tsx",
      "app/javascript/task/components/nested_list.tsx",
      "app/javascript/task/components/parent_list_item.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/show_view.tsx",
      "app/javascript/task/components/sub_tasks_table.tsx",
      "app/javascript/task/components/table_headers.tsx",
      "app/javascript/task/components/task_display.tsx",
      "app/javascript/task/components/task_row.tsx",
      "app/javascript/task/components/task_title.tsx",
      "app/javascript/task/components/tree_view.tsx",
      "app/javascript/task/containers/parent_task_bread_crumbs.tsx",
      "app/javascript/task/selectors.ts",
      "app/javascript/timeframe/components/list_view.tsx",
      "app/javascript/timeframe/components/section.tsx",
      "app/javascript/timeframe/components/task_row.tsx",
    ],
    rules: {
      "@typescript-eslint/consistent-type-definitions": "off",
    },
  },
  // Offense count: 60
  {
    files: [
      "app/javascript/_common/create_app_store.ts",
      "app/javascript/_common/create_basic_reducer.ts",
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/crash_site_onerror.ts",
      "app/javascript/helpers/ajax.ts",
      "app/javascript/helpers/debug.ts",
      "app/javascript/helpers/time_balancer.ts",
      "app/javascript/route/action_creators.ts",
      "app/javascript/route/helpers.ts",
      "app/javascript/route/reducer.ts",
      "app/javascript/route/routes.ts",
      "app/javascript/tag/action_creators.ts",
      "app/javascript/tag/components/edit_view.tsx",
      "app/javascript/tag/containers/buttons.ts",
      "app/javascript/tag/containers/edit_view.ts",
      "app/javascript/tag/reducer.ts",
      "app/javascript/tag/selectors.ts",
      "app/javascript/task/action_creators.ts",
      "app/javascript/task/components/delete_button.tsx",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/components/main_buttons.tsx",
      "app/javascript/task/components/task_display.tsx",
      "app/javascript/task/containers/focus_view.ts",
      "app/javascript/task/containers/list_view.ts",
      "app/javascript/task/containers/parent_task_bread_crumbs.tsx",
      "app/javascript/task/containers/show_view.ts",
      "app/javascript/task/containers/tree_view.ts",
      "app/javascript/task/reducer.ts",
      "app/javascript/timeframe/components/task_row.tsx",
      "app/javascript/timeframe/utils.ts",
      "spec/javascript/task/components/focus_view_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/explicit-function-return-type": "off",
    },
  },
  // Offense count: 24
  {
    files: [
      "app/javascript/_common/create_app_store.ts",
      "app/javascript/_common/create_basic_reducer.ts",
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/helpers/ajax.ts",
      "app/javascript/helpers/debug.ts",
      "app/javascript/helpers/time_balancer.ts",
      "app/javascript/route/action_creators.ts",
      "app/javascript/route/helpers.ts",
      "app/javascript/tag/action_creators.ts",
      "app/javascript/tag/components/edit_view.tsx",
      "app/javascript/task/action_creators.ts",
      "app/javascript/task/components/delete_button.tsx",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/components/main_buttons.tsx",
      "app/javascript/task/components/task_display.tsx",
      "app/javascript/timeframe/components/task_row.tsx",
    ],
    rules: {
      "@typescript-eslint/explicit-module-boundary-types": "off",
    },
  },
  // Offense count: 11
  {
    files: [
      "app/javascript/helpers/debug.ts",
      "app/javascript/route/helpers.ts",
      "app/javascript/task/containers/parent_task_bread_crumbs.tsx",
      "app/javascript/timeframe/store.ts",
      "app/javascript/timeframe/utils.ts",
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/init-declarations": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/crash_site_onerror.ts",
    ],
    rules: {
      "@typescript-eslint/max-params": "off",
    },
  },
  // Offense count: 5
  {
    files: [
      "app/javascript/@types/timeframe.d.ts",
      "app/javascript/controllers/react_controller.tsx",
      "spec/javascript/_test_helpers/fake_notification.ts",
    ],
    rules: {
      "@typescript-eslint/member-ordering": "off",
    },
  },
  // Offense count: 20
  {
    files: [
      "app/javascript/@types/task.d.ts",
      "app/javascript/@types/timeframe.d.ts",
    ],
    rules: {
      "@typescript-eslint/method-signature-style": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/crash_site_onerror.ts",
    ],
    rules: {
      "@typescript-eslint/no-base-to-string": "off",
    },
  },
  // Offense count: 22
  {
    files: [
      "app/javascript/_common/create_basic_reducer.ts",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/timeframe/store.ts",
      "spec/javascript/route/reducer_spec.ts",
      "spec/javascript/tag/reducer_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/reducer_spec.tsx",
      "spec/javascript/timeframe/store_spec.ts",
    ],
    rules: {
      "@typescript-eslint/no-confusing-void-expression": "off",
    },
  },
  // Offense count: 6
  {
    files: [
      "app/javascript/_common/create_app_store.ts",
      "app/javascript/task/components/edit_title_form.tsx",
      "spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx",
      "spec/javascript/task/containers/show_view_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/no-deprecated": "off",
    },
  },
  // Offense count: 13
  {
    files: [
      "app/javascript/@types/globals.d.ts",
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/helpers/debug.ts",
      "app/javascript/helpers/request.ts",
      "spec/javascript/_test_helpers/factories/state.ts",
      "spec/javascript/_test_helpers/shims.ts",
      "spec/javascript/helpers/debug_spec.ts",
      "spec/javascript/setup.ts",
    ],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  // Offense count: 3
  {
    files: [
      "app/javascript/helpers/request.ts",
      "app/javascript/timeframe/components/list_view.tsx",
    ],
    rules: {
      "@typescript-eslint/no-floating-promises": "off",
    },
  },
  // Offense count: 3
  {
    files: [
      "app/javascript/task/action_creators.ts",
    ],
    rules: {
      "@typescript-eslint/no-misused-promises": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/_common/create_merged_reducer.ts",
    ],
    rules: {
      "@typescript-eslint/no-redundant-type-constituents": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/application.tsx",
    ],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
  // Offense count: 6
  {
    files: [
      "app/javascript/helpers/authenticity_token.ts",
      "app/javascript/tag/containers/buttons.ts",
      "app/javascript/task/bulk_store.ts",
      "app/javascript/task/components/task_display.tsx",
      "app/javascript/task/selectors.ts",
      "app/javascript/task/store.ts",
    ],
    rules: {
      "@typescript-eslint/no-unnecessary-condition": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "vitest.config.ts",
    ],
    rules: {
      "@typescript-eslint/no-unnecessary-template-expression": "off",
    },
  },
  // Offense count: 2
  {
    files: [
      "app/javascript/_common/create_basic_reducer.ts",
      "app/javascript/helpers/debug.ts",
    ],
    rules: {
      "@typescript-eslint/no-unnecessary-type-parameters": "off",
    },
  },
  // Offense count: 6
  {
    files: [
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/task/action_creators.ts",
    ],
    rules: {
      "@typescript-eslint/no-unsafe-argument": "off",
    },
  },
  // Offense count: 13
  {
    files: [
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/helpers/debug.ts",
      "app/javascript/task/action_creators.ts",
      "spec/javascript/_test_helpers/factories/state.ts",
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/no-unsafe-assignment": "off",
    },
  },
  // Offense count: 3
  {
    files: [
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/timeframe/store_spec.ts",
    ],
    rules: {
      "@typescript-eslint/no-unsafe-call": "off",
    },
  },
  // Offense count: 10
  {
    files: [
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/helpers/debug.ts",
      "spec/javascript/_test_helpers/shims.ts",
      "spec/javascript/helpers/debug_spec.ts",
      "spec/javascript/setup.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/timeframe/store_spec.ts",
    ],
    rules: {
      "@typescript-eslint/no-unsafe-member-access": "off",
    },
  },
  // Offense count: 5
  {
    files: [
      "app/javascript/_common/create_merged_reducer.ts",
      "app/javascript/helpers/debug.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/timeframe/store_spec.ts",
    ],
    rules: {
      "@typescript-eslint/no-unsafe-return": "off",
    },
  },
  // Offense count: 22
  {
    files: [
      "app/javascript/helpers/debug.ts",
      "spec/javascript/_test_helpers/shims.ts",
      "spec/javascript/helpers/debug_spec.ts",
      "spec/javascript/setup.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/timeframe/components/list_view_spec.tsx",
      "spec/javascript/timeframe/store_spec.ts",
    ],
    rules: {
      "@typescript-eslint/no-unsafe-type-assertion": "off",
    },
  },
  // Offense count: 2
  {
    files: [
      "app/javascript/crash_site_onerror.ts",
    ],
    rules: {
      "@typescript-eslint/no-use-before-define": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/prefer-destructuring": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/@types/globals.d.ts",
    ],
    rules: {
      "@typescript-eslint/prefer-function-type": "off",
    },
  },
  // Offense count: 8
  {
    files: [
      "app/javascript/task/components/task_row.tsx",
      "app/javascript/task/reducer.ts",
      "app/javascript/task/store.ts",
      "app/javascript/timeframe/components/task_row.tsx",
      "spec/javascript/_test_helpers/factories/state.ts",
      "spec/javascript/_test_helpers/factories/task.ts",
    ],
    rules: {
      "@typescript-eslint/prefer-nullish-coalescing": "off",
    },
  },
  // Offense count: 4
  {
    files: [
      "app/javascript/crash_site_onerror.ts",
      "app/javascript/helpers/authenticity_token.ts",
      "app/javascript/tag/components/edit_view.tsx",
      "app/javascript/tag/reducer.ts",
    ],
    rules: {
      "@typescript-eslint/prefer-optional-chain": "off",
    },
  },
  // Offense count: 8
  {
    files: [
      "app/javascript/helpers/ajax.ts",
      "app/javascript/timeframe/store.ts",
      "spec/javascript/_test_helpers/fake_notification.ts",
    ],
    rules: {
      "@typescript-eslint/promise-function-async": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/crash_site_onerror.ts",
    ],
    rules: {
      "@typescript-eslint/restrict-template-expressions": "off",
    },
  },
  // Offense count: 32
  {
    files: [
      "app/javascript/crash_site_onerror.ts",
      "app/javascript/helpers/authenticity_token.ts",
      "app/javascript/helpers/debug.ts",
      "app/javascript/tag/components/buttons.tsx",
      "app/javascript/tag/containers/buttons.ts",
      "app/javascript/task/action_creators.ts",
      "app/javascript/task/bulk_store.ts",
      "app/javascript/task/components/checkbox.tsx",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/components/show_view.tsx",
      "app/javascript/task/components/task_display.tsx",
      "app/javascript/task/components/task_row.tsx",
      "app/javascript/task/components/task_title.tsx",
      "app/javascript/task/reducer.ts",
      "app/javascript/task/selectors.ts",
      "app/javascript/task/store.ts",
      "app/javascript/timeframe/components/task_row.tsx",
      "spec/javascript/_test_helpers/factories/task.ts",
    ],
    rules: {
      "@typescript-eslint/strict-boolean-expressions": "off",
    },
  },
  // Offense count: 38
  {
    files: [
      "app/javascript/_common/globals.ts",
      "app/javascript/application.tsx",
      "app/javascript/tag/action_creators.ts",
      "app/javascript/task/action_creators.ts",
      "spec/javascript/_test_helpers/fake_notification.ts",
      "spec/javascript/app_store_spec.ts",
      "spec/javascript/task/components/checkbox_spec.tsx",
      "spec/javascript/task/components/focus_view_spec.tsx",
      "spec/javascript/task/components/list_view_spec.tsx",
      "spec/javascript/task/components/nested_list_spec.tsx",
      "spec/javascript/task/components/parent_list_item_spec.tsx",
      "spec/javascript/task/components/postpone_button_spec.tsx",
      "spec/javascript/task/components/show_view_spec.tsx",
      "spec/javascript/task/components/sub_tasks_table_spec.tsx",
      "spec/javascript/task/components/task_row_spec.tsx",
      "spec/javascript/timeframe/components/task_row_spec.tsx",
      "spec/javascript/timeframe/store_spec.ts",
    ],
    rules: {
      "@typescript-eslint/strict-void-return": "off",
    },
  },
  // Offense count: 44
  {
    files: [
      "app/javascript/tag/components/buttons.tsx",
      "app/javascript/tag/components/edit_view.tsx",
      "app/javascript/tag/components/rule_row.tsx",
      "app/javascript/task/components/delete_button.tsx",
      "app/javascript/task/components/done_button.tsx",
      "app/javascript/task/components/edit_title_form.tsx",
      "app/javascript/task/components/focus_view.tsx",
      "app/javascript/task/components/leaf_list_item.tsx",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/components/nested_list.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/task_row.tsx",
      "app/javascript/timeframe/components/list_view.tsx",
      "app/javascript/timeframe/components/section.tsx",
      "app/javascript/timeframe/components/task_row.tsx",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/components/list_view_spec.tsx",
    ],
    rules: {
      "@typescript-eslint/unbound-method": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/_test_helpers/vitest.d.ts",
    ],
    rules: {
      "@typescript-eslint/unified-signatures": "off",
    },
  },
  // Offense count: 53
  {
    files: [
      "app/javascript/application.tsx",
      "app/javascript/helpers/ajax.ts",
      "app/javascript/helpers/to_english.ts",
      "app/javascript/route/helpers.ts",
      "app/javascript/tag/action_creators.ts",
      "app/javascript/tag/components/edit_view.tsx",
      "app/javascript/tag/components/rule_row.tsx",
      "app/javascript/tag/selectors.ts",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/sub_tasks_table.tsx",
      "app/javascript/task/selectors.ts",
      "app/javascript/task/store.ts",
      "app/javascript/timeframe/store.ts",
      "spec/javascript/helpers/grab_spec.ts",
      "spec/javascript/tag/action_creators_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/components/focus_view_spec.tsx",
      "spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx",
      "spec/javascript/task/containers/show_view_spec.tsx",
      "spec/javascript/timeframe/store_spec.ts",
    ],
    rules: {
      "arrow-body-style": "off",
    },
  },
  // Offense count: 18
  {
    files: [
      "app/javascript/@types/globals.d.ts",
      "app/javascript/controllers/dialog_controller.ts",
      "app/javascript/helpers/authenticity_token.ts",
      "app/javascript/tag/components/rule_row.tsx",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/task/components/task_row.tsx",
      "app/javascript/task/containers/parent_task_bread_crumbs.tsx",
      "app/javascript/timeframe/components/task_row.tsx",
      "spec/javascript/_test_helpers/fake_notification.ts",
      "spec/javascript/helpers/debug_spec.ts",
      "spec/javascript/setup.ts",
    ],
    rules: {
      "capitalized-comments": "off",
    },
  },
  // Offense count: 3
  {
    files: [
      "app/javascript/_common/globals.ts",
      "app/javascript/application.tsx",
    ],
    rules: {
      "id-length": "off",
    },
  },
  // Offense count: 2
  {
    files: [
      "vitest.config.ts",
    ],
    rules: {
      "max-len": "off",
    },
  },
  // Offense count: 7
  {
    files: [
      "spec/javascript/helpers/time_balancer_spec.ts",
      "spec/javascript/tag/selectors_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/components/list_view_spec.tsx",
      "spec/javascript/timeframe/store_spec.ts",
    ],
    rules: {
      "max-lines-per-function": "off",
    },
  },
  // Offense count: 9
  {
    files: [
      "app/javascript/helpers/debug.ts",
      "app/javascript/helpers/time_balancer.ts",
      "app/javascript/task/components/list_view.tsx",
      "app/javascript/timeframe/utils.ts",
      "spec/javascript/tag/selectors_spec.ts",
      "spec/javascript/task/components/list_view_spec.tsx",
      "spec/javascript/timeframe/store_spec.ts",
    ],
    rules: {
      "max-statements": "off",
    },
  },
  // Offense count: 3
  {
    files: [
      "spec/javascript/_test_helpers/fake_notification.ts",
      "spec/javascript/helpers/debug_spec.ts",
      "spec/javascript/setup.ts",
    ],
    rules: {
      "no-inline-comments": "off",
    },
  },
  // Offense count: 2
  {
    files: [
      "app/javascript/tag/reducer.ts",
      "spec/javascript/_test_helpers/factories/task.ts",
    ],
    rules: {
      "no-prototype-builtins": "off",
    },
  },
  // Offense count: 19
  {
    files: [
      "app/javascript/helpers/debug.ts",
      "app/javascript/helpers/to_english.ts",
      "app/javascript/tag/components/button.tsx",
      "app/javascript/tag/components/rule_row.tsx",
      "app/javascript/tag/selectors.ts",
      "app/javascript/task/components/done_button.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/task_row.tsx",
      "app/javascript/timeframe/components/section.tsx",
      "app/javascript/timeframe/components/task_row.tsx",
      "app/javascript/timeframe/utils.ts",
    ],
    rules: {
      "no-ternary": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/helpers/request.ts",
    ],
    rules: {
      "no-void": "off",
    },
  },
  // Offense count: 15
  {
    files: [
      "app/javascript/route/routes.ts",
      "app/javascript/tag/components/edit_view.tsx",
      "app/javascript/tag/selectors.ts",
      "app/javascript/task/action_creators.ts",
      "app/javascript/task/components/task_row.tsx",
      "app/javascript/task/containers/list_view.ts",
      "app/javascript/task/reducer.ts",
      "app/javascript/timeframe/components/list_view.tsx",
      "app/javascript/timeframe/utils.ts",
      "spec/javascript/route/action_creators_spec.ts",
      "spec/javascript/tag/action_creators_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/reducer_spec.tsx",
      "spec/javascript/task/selectors_spec.tsx",
    ],
    rules: {
      "sort-imports": "off",
    },
  },
  // Offense count: 173
  {
    files: [
      "app/javascript/helpers/ajax.ts",
      "app/javascript/helpers/debug.ts",
      "app/javascript/helpers/request.ts",
      "app/javascript/helpers/time_balancer.ts",
      "app/javascript/route/action_creators.ts",
      "app/javascript/tag/action_creators.ts",
      "app/javascript/tag/components/button.tsx",
      "app/javascript/tag/components/edit_view.tsx",
      "app/javascript/tag/selectors.ts",
      "app/javascript/task/action_creators.ts",
      "app/javascript/task/bulk_store.ts",
      "app/javascript/task/components/delete_button.tsx",
      "app/javascript/task/components/edit_title_form.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/sub_tasks_table.tsx",
      "app/javascript/task/containers/focus_view.ts",
      "app/javascript/task/containers/list_view.ts",
      "app/javascript/task/reducer.ts",
      "app/javascript/task/selectors.ts",
      "app/javascript/task/store.ts",
      "app/javascript/timeframe/components/list_view.tsx",
      "app/javascript/timeframe/name_map.ts",
      "app/javascript/timeframe/store.ts",
      "app/javascript/timeframe/utils.ts",
      "spec/javascript/_test_helpers/factories/state.ts",
      "spec/javascript/_test_helpers/factories/tag.ts",
      "spec/javascript/_test_helpers/factories/task.ts",
      "spec/javascript/_test_helpers/factories/timeframe.ts",
      "spec/javascript/app_reducer_spec.ts",
      "spec/javascript/app_store_spec.ts",
      "spec/javascript/helpers/time_balancer_spec.ts",
      "spec/javascript/route/action_creators_spec.ts",
      "spec/javascript/route/reducer_spec.ts",
      "spec/javascript/tag/action_creators_spec.ts",
      "spec/javascript/tag/components/button_spec.tsx",
      "spec/javascript/tag/components/buttons_spec.tsx",
      "spec/javascript/tag/components/edit_view_spec.tsx",
      "spec/javascript/tag/components/rule_row_spec.tsx",
      "spec/javascript/tag/reducer_spec.ts",
      "spec/javascript/tag/selectors_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/components/show_view_spec.tsx",
      "spec/javascript/task/components/sub_tasks_table_spec.tsx",
      "spec/javascript/task/components/task_row_spec.tsx",
      "spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx",
      "spec/javascript/task/reducer_spec.tsx",
      "spec/javascript/task/selectors_spec.tsx",
      "spec/javascript/timeframe/components/list_view_spec.tsx",
      "spec/javascript/timeframe/components/task_row_spec.tsx",
      "spec/javascript/timeframe/store_spec.ts",
    ],
    rules: {
      "sort-keys": "off",
    },
  },
  // Offense count: 173
  {
    files: [
      "app/javascript/helpers/ajax.ts",
      "app/javascript/helpers/debug.ts",
      "app/javascript/helpers/request.ts",
      "app/javascript/helpers/time_balancer.ts",
      "app/javascript/route/action_creators.ts",
      "app/javascript/tag/action_creators.ts",
      "app/javascript/tag/components/button.tsx",
      "app/javascript/tag/components/edit_view.tsx",
      "app/javascript/tag/selectors.ts",
      "app/javascript/task/action_creators.ts",
      "app/javascript/task/bulk_store.ts",
      "app/javascript/task/components/delete_button.tsx",
      "app/javascript/task/components/edit_title_form.tsx",
      "app/javascript/task/components/postpone_button.tsx",
      "app/javascript/task/components/sub_tasks_table.tsx",
      "app/javascript/task/containers/focus_view.ts",
      "app/javascript/task/containers/list_view.ts",
      "app/javascript/task/reducer.ts",
      "app/javascript/task/selectors.ts",
      "app/javascript/task/store.ts",
      "app/javascript/timeframe/components/list_view.tsx",
      "app/javascript/timeframe/name_map.ts",
      "app/javascript/timeframe/store.ts",
      "app/javascript/timeframe/utils.ts",
      "spec/javascript/_test_helpers/factories/state.ts",
      "spec/javascript/_test_helpers/factories/tag.ts",
      "spec/javascript/_test_helpers/factories/task.ts",
      "spec/javascript/_test_helpers/factories/timeframe.ts",
      "spec/javascript/app_reducer_spec.ts",
      "spec/javascript/app_store_spec.ts",
      "spec/javascript/helpers/time_balancer_spec.ts",
      "spec/javascript/route/action_creators_spec.ts",
      "spec/javascript/route/reducer_spec.ts",
      "spec/javascript/tag/action_creators_spec.ts",
      "spec/javascript/tag/components/button_spec.tsx",
      "spec/javascript/tag/components/buttons_spec.tsx",
      "spec/javascript/tag/components/edit_view_spec.tsx",
      "spec/javascript/tag/components/rule_row_spec.tsx",
      "spec/javascript/tag/reducer_spec.ts",
      "spec/javascript/tag/selectors_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/components/show_view_spec.tsx",
      "spec/javascript/task/components/sub_tasks_table_spec.tsx",
      "spec/javascript/task/components/task_row_spec.tsx",
      "spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx",
      "spec/javascript/task/reducer_spec.tsx",
      "spec/javascript/task/selectors_spec.tsx",
      "spec/javascript/timeframe/components/list_view_spec.tsx",
      "spec/javascript/timeframe/components/task_row_spec.tsx",
      "spec/javascript/timeframe/store_spec.ts",
    ],
    rules: {
      "sort-keys-fix/sort-keys-fix": "off",
    },
  },
  // Offense count: 11
  {
    files: [
      "spec/javascript/tag/selectors_spec.ts",
      "spec/javascript/timeframe/store_spec.ts",
    ],
    rules: {
      "vitest/max-expects": "off",
    },
  },
  // Offense count: 7
  {
    files: [
      "spec/javascript/helpers/debug_spec.ts",
      "spec/javascript/route/action_creators_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "vitest/no-hooks": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "vitest/no-standalone-expect": "off",
    },
  },
  // Offense count: 9
  {
    files: [
      "spec/javascript/app_store_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/components/checkbox_spec.tsx",
      "spec/javascript/timeframe/store_spec.ts",
    ],
    rules: {
      "vitest/prefer-called-with": "off",
    },
  },
  // Offense count: 4
  {
    files: [
      "spec/javascript/helpers/time_balancer_spec.ts",
      "spec/javascript/helpers/to_english_spec.ts",
      "spec/javascript/task/containers/parent_task_bread_crumbs_spec.tsx",
    ],
    rules: {
      "vitest/prefer-lowercase-title": "off",
    },
  },
  // Offense count: 4
  {
    files: [
      "spec/javascript/task/action_creators_spec.tsx",
    ],
    rules: {
      "vitest/prefer-mock-promise-shorthand": "off",
    },
  },
  // Offense count: 67
  {
    files: [
      "spec/javascript/app_reducer_spec.ts",
      "spec/javascript/app_store_spec.ts",
      "spec/javascript/helpers/time_balancer_spec.ts",
      "spec/javascript/route/action_creators_spec.ts",
      "spec/javascript/route/helpers_spec.ts",
      "spec/javascript/route/reducer_spec.ts",
      "spec/javascript/tag/action_creators_spec.ts",
      "spec/javascript/tag/reducer_spec.ts",
      "spec/javascript/tag/selectors_spec.ts",
      "spec/javascript/task/action_creators_spec.tsx",
      "spec/javascript/task/reducer_spec.tsx",
      "spec/javascript/task/selectors_spec.tsx",
      "spec/javascript/timeframe/store_spec.ts",
    ],
    rules: {
      "vitest/prefer-strict-equal": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/application_spec.ts",
    ],
    rules: {
      "vitest/prefer-to-be": "off",
    },
  },
  // Offense count: 5
  {
    files: [
      "app/javascript/application.tsx",
      "spec/javascript/_test_helpers/factories/id.ts",
    ],
    rules: {
      "vitest/require-hook": "off",
    },
  },
];

export default config;
