root: true
# have to include `plugin:react/recommended` to avoid errors
extends:
  - eslint:all
  - plugin:eslint-plugin-jsx-a11y/recommended
  - plugin:import/errors
  - plugin:react/all
plugins: [eslint-plugin-jsx-a11y, import, react]
parserOptions:
  sourceType: module
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
env:
  browser: true
  es6: true
  node: true
globals:
  $: true
settings:
  import/resolver:
    node:
      moduleDirectory: [app, node_modules]
rules:
  ### to enable/improve
  init-declarations: off
  jsx-a11y/click-events-have-key-events: off
  jsx-a11y/href-no-hash: off
  jsx-a11y/label-has-for: off
  jsx-a11y/no-onchange: off
  jsx-a11y/no-static-element-interactions: off
  jsx-a11y/onclick-has-role: off
  max-len: [error, 112]
  max-statements: [error, { max: 14 }]
  no-magic-numbers: off
  react/forbid-component-props: off
  react/forbid-prop-types: off
  react/jsx-boolean-value: off
  react/jsx-filename-extension: off
  react/jsx-sort-props: off
  react/no-multi-comp: off
  react/no-set-state: off
  # https://github.com/yannickcr/eslint-plugin-react/issues/811
  react/no-unused-prop-types: off
  react/prefer-es6-class: off
  react/require-default-props: off
  sort-imports: off # https://github.com/eslint/eslint/issues/7766
  sort-keys: off

  ### departures from default
  brace-style: [error, 1tbs, { allowSingleLine: true }]
  comma-dangle: [error, always-multiline]
  func-style: [error, declaration]
  id-length: [error, { exceptions: [_, $] }]
  indent: [error, 2]
  jsx-quotes: [error, prefer-single]
  max-statements-per-line: [error, { max: 2 }]
  multiline-ternary: [error, never]
  no-extra-parens: [error, all, { nestedBinaryExpressions: false }]
  no-multiple-empty-lines: [error, { max: 1, maxEOF: 0, maxBOF: 0 }]
  no-underscore-dangle: [error, { allowAfterThis: true }]
  object-property-newline: [error, { allowMultiplePropertiesPerLine: true }]
  one-var: [error, never]
  padded-blocks: [error, never]
  prefer-arrow-callback: [error, { allowNamedFunctions: true }]
  prefer-destructuring: [error, { array: false }]
  quote-props: [error, as-needed, { keywords: true }]
  quotes: [error, single]
  react/jsx-indent-props: [error, 2]
  react/jsx-indent: [error, 2]
  react/jsx-wrap-multilines: [error, { declaration: false }]
  space-before-function-paren: [error, { anonymous: always, named: never }]
  spaced-comment: [error, always, { markers: [=] }]

  ### dumb rules
  capitalized-comments: off
  no-inline-comments: off
  no-ternary: off
  react/jsx-handler-names: off
  react/jsx-max-props-per-line: off
  require-jsdoc: off
