AllCops:
  Include:
    - !ruby/regexp /.*\.rake\z/
    - Gemfile
    - Guardfile
    - Rakefile
    - config.ru
    - !ruby/regexp /.*\.ruby\z/
  Exclude:
    - db/schema.rb
  RunRailsCops: true

AccessModifierIndentation:
  EnforcedStyle: outdent

Output:
  Exclude:
    - lib/tasks/fix_counters.rake

CollectionMethods:
  PreferredMethods:
    collect: map
    collect!: map!
    inject: reduce
    find: detect
    find_all: select

Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

TrailingComma:
  EnforcedStyleForMultiline: comma

# enable or confirm the rules below
# ............................................................................ #

MethodLength:
  Max: 12

Metrics/AbcSize:
  Max: 26

# https://github.com/bbatsov/rubocop/issues/1568
EmptyLinesAroundBlockBody:
  Enabled: false
