AllCops:
  Include:
    - !ruby/regexp /.*\.rake/
    - Gemfile
    # - Guardfile
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
  RunRailsCops: true

AccessModifierIndentation:
  EnforcedStyle: outdent

Output:
  Exclude:
    - lib/tasks/fix_counters.rake

ActionFilter:
  Enabled: false

CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    find: 'detect'
    find_all: 'select'

Documentation:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma

# enable or confirm the rules below
# ............................................................................ #

MethodLength:
  Max: 12
