inherit_from: .rubocop_todo.yml

inherit_mode:
  merge: [Exclude]

require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec

AllCops:
  EnabledByDefault: true
  DefaultFormatter: fuubar
  DisplayCopNames: true
  Exclude:
    - vendor/**/*
    - db/schema.rb
    - !ruby/regexp /node_modules\/.*/

Rails: { Enabled: true }

# ............................................................................ #
#
# departures from default
#
# ............................................................................ #

Layout/LineLength: { Max: 80, AutoCorrect: true }
Metrics/BlockLength: { AllowedMethods: [configure, context, describe, draw] }
Naming/VariableNumber: { EnforcedStyle: snake_case }
RSpec/FilePath: { Exclude: [spec/matchers/**/*] }
RSpec/ContextWording: { Prefixes: [when] }
Style/CollectionMethods:
  PreferredMethods:
    collect: map
    collect!: map!
    inject: reduce
    find: detect
    find_all: select
Style/HashSyntax: { Exclude: [app/views/**/*.haml*] } # https://github.com/sds/haml-lint/issues/372
Style/MethodCallWithArgsParentheses:
  AllowedMethods:
    - and
    - describe
    - to
Style/SymbolArray: { EnforcedStyle: brackets }
Style/TrailingCommaInArguments: { EnforcedStyleForMultiline: comma }
Style/TrailingCommaInArrayLiteral: { EnforcedStyleForMultiline: comma }
Style/TrailingCommaInHashLiteral: { EnforcedStyleForMultiline: comma }
Style/WordArray: { EnforcedStyle: brackets }

# ............................................................................ #
#
# intentionally disabled
#
# ............................................................................ #

Bundler/GemComment: { Enabled: false }
Bundler/GemVersion: { Enabled: false }
Layout/SingleLineBlockChain: { Enabled: false }
Lint/AmbiguousOperatorPrecedence: { Enabled: false }
Lint/ConstantResolution: { Enabled: false }
Rails/BulkChangeTable: { Enabled: false }
Rails/HasManyOrHasOneDependent: { Enabled: false }
RSpec/IndexedLet: { Enabled: false }
Style/Copyright: { Enabled: false }
Style/Documentation: { Enabled: false }
Style/DocumentationMethod: { Enabled: false }
Style/InlineComment: { Enabled: false }
Style/MissingElse: { Enabled: false }
Style/RequireOrder: { Enabled: false }
