require:
  rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  DefaultFormatter: fuubar
  DisplayCopNames: true
  Include:
    - !ruby/regexp /.*\.rake\z/
    - Gemfile
    - Guardfile
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
    - !ruby/regexp /node_modules\/.*/

Rails:
  Enabled: true

AccessModifierIndentation:
  EnforcedStyle: outdent

Output:
  Exclude:
    - lib/tasks/fix_counters.rake

CollectionMethods:
  PreferredMethods:
    collect: map
    collect!: map!
    inject: reduce
    find: detect
    find_all: select

Documentation:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

ClassLength:
  Max: 115

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Style/LambdaCall:
  EnforcedStyle: braces

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# enable or confirm the rules below
# ............................................................................ #

Style/RegexpLiteral:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

MethodLength:
  Max: 12

Metrics/AbcSize:
  Max: 26

# https://github.com/bbatsov/rubocop/issues/1568
EmptyLinesAroundBlockBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/VariableNumber:
  EnforcedStyle: snake_case

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false
