require:
  - ./linters/rubocop/cop/rspec/no_before_hook

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge: [Exclude]

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-i18n
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  EnabledByDefault: true
  DefaultFormatter: fuubar
  DisplayCopNames: true
  Exclude:
    - vendor/**/*
    - db/schema.rb
    - !ruby/regexp /node_modules\/.*/
    - config/environments/development.rb

Rails: { Enabled: true }

# ............................................................................ #
#
# departures from default
#
# ............................................................................ #

Layout/LineLength: { Max: 80, AutoCorrect: true }
Metrics/BlockLength: { AllowedMethods: [configure, context, describe, draw] }
Metrics/MethodLength: { Exclude: [db/migrate/**/*.rb] }
Naming/VariableNumber: { EnforcedStyle: snake_case }
Rails/FilePath: { Exclude: [spec/matchers/**/*], EnforcedStyle: slashes }
RSpec/ContextWording: { Prefixes: [when] }
RSpec/MessageExpectation: { EnforcedStyle: expect }
RSpec/MultipleExpectations:
  Exclude:
    - spec/system/**/*.rb
RSpec/MultipleMemoizedHelpers:
  Max: 0
  AllowSubject: false
  Exclude:
    - spec/linters/rubocop/**/*.rb
Style/ArrayFirstLast: { Exclude: [Guardfile] }
Style/CollectionMethods:
  PreferredMethods:
    collect: map
    collect!: map!
    inject: reduce
    find: detect
    find_all: select
Style/HashSyntax: { Exclude: [app/views/**/*.haml*] } # https://github.com/sds/haml-lint/issues/372
Style/MethodCallWithArgsParentheses:
  AllowedMethods:
    - and
    - describe
    - to
Style/StringLiterals: { EnforcedStyle: double_quotes }
Style/StringLiteralsInInterpolation: { EnforcedStyle: double_quotes }
Style/SymbolArray: { EnforcedStyle: brackets }
Style/TrailingCommaInArguments: { EnforcedStyleForMultiline: comma }
Style/TrailingCommaInArrayLiteral: { EnforcedStyleForMultiline: comma }
Style/TrailingCommaInHashLiteral: { EnforcedStyleForMultiline: comma }
Style/WordArray: { EnforcedStyle: brackets }

I18n/GetText/DecorateString:
  Exclude:
    - linters/**/*.rb
I18n/RailsI18n/DecorateString:
  Exclude:
    - linters/**/*.rb

# ............................................................................ #
#
# intentionally disabled
#
# ............................................................................ #

Bundler/GemComment: { Enabled: false }
Bundler/GemVersion: { Enabled: false }
Capybara/AmbiguousClick: { Enabled: false }
# https://github.com/rubocop/rubocop-i18n/issues/69
I18n/GetText/DecorateFunctionMessage: { Enabled: false } # crashes on .() syntax
I18n/GetText/DecorateStringFormattingUsingInterpolation: { Enabled: false } # crashes on .() syntax
I18n/GetText/DecorateStringFormattingUsingPercent: { Enabled: false } # crashes on .() syntax
Layout/SingleLineBlockChain: { Enabled: false }
Lint/AmbiguousOperatorPrecedence: { Enabled: false }
Lint/ConstantResolution: { Enabled: false }
Rails/BulkChangeTable: { Enabled: false }
Rails/HasManyOrHasOneDependent: { Enabled: false }
Rails/OrderById: { Enabled: false }
Rails/RedundantPresenceValidationOnBelongsTo: { Enabled: false }
Rails/SchemaComment: { Enabled: false }
RSpec/AlignLeftLetBrace: { Enabled: false }
RSpec/AlignRightLetBrace: { Enabled: false }
RSpec/IndexedLet: { Enabled: false }
Style/CommentedKeyword: { Enabled: false }
Style/ConstantVisibility: { Enabled: false }
Style/Copyright: { Enabled: false }
Style/Documentation: { Enabled: false }
Style/DocumentationMethod: { Enabled: false }
Style/InlineComment: { Enabled: false }
Style/MissingElse: { Enabled: false }
Style/RequireOrder: { Enabled: false }
