AllCops:
  Excludes:
    - db/schema.rb
    - db/migrate/*
  RunRailsCops: true

AccessModifierIndentation:
  EnforcedStyle: outdent

CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    find: 'detect'
    find_all: 'select'

Documentation:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma

# enable once they add on option to include line length
IfUnlessModifier:
  Enabled: false

# come back to this one after some more research
Encoding:
  Enabled: false

# enable or confirm the rules below
# ............................................................................ #

# Offence count: 34
LineLength:
  Max: 174

# Offence count: 4
# Configuration parameters: CountComments.
MethodLength:
  Max: 22
# 
# # Offence count: 1
# # Configuration parameters: EnforcedStyleForMultiline, SupportedStyles.
# # Offence count: 8
# UselessAssignment:
#   Enabled: false
# 
# Offence count: 6
# Cop supports --auto-correct.
WordArray:
  MinSize: 3
