inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  EnabledByDefault: true
  DefaultFormatter: fuubar
  DisplayCopNames: true
  Exclude:
    - vendor/**/*
    - db/schema.rb
    - !ruby/regexp /node_modules\/.*/

Rails: { Enabled: true }

# ............................................................................ #
# departures from default
# ............................................................................ #

# https://github.com/sds/haml-lint/issues/315
Layout/LineLength: { Max: 80, AutoCorrect: true }

RSpec/FilePath: { Exclude: [spec/matchers/**/*] }
RSpec/ContextWording: { Prefixes: [when] }
Style/CollectionMethods:
  PreferredMethods:
    collect: map
    collect!: map!
    inject: reduce
    find: detect
    find_all: select
Style/TrailingCommaInArguments: { EnforcedStyleForMultiline: comma }
Style/TrailingCommaInArrayLiteral: { EnforcedStyleForMultiline: comma }
Style/TrailingCommaInHashLiteral: { EnforcedStyleForMultiline: comma }

# ............................................................................ #
# intentionally disabled
# ............................................................................ #

Bundler/GemComment: { Enabled: false }
Bundler/GemVersion: { Enabled: false }
Lint/AmbiguousOperatorPrecedence: { Enabled: false }
Rails/BulkChangeTable: { Enabled: false }
Rails/HasManyOrHasOneDependent: { Enabled: false }
Style/Copyright: { Enabled: false }
Style/Documentation: { Enabled: false }
Style/InlineComment: { Enabled: false }
Style/MissingElse: { Enabled: false }
