extends: stylelint-config-standard-scss
rules:
  ##############################################################################
  #
  #                          Rules to enabled
  #
  ##############################################################################
  alpha-value-notation: null
  color-function-notation: null
  selector-class-pattern: null
  selector-pseudo-element-colon-notation: null
  string-quotes: null
