extends: stylelint-config-standard-scss
rules:
  ##############################################################################
  #
  #                          Rules to enabled
  #
  ##############################################################################
  scss/at-extend-no-missing-placeholder: null
  selector-class-pattern: null
  selector-pseudo-element-colon-notation: null
  string-quotes: null
