extends:
  - stylelint-config-property-sort-order-smacss
  - stylelint-config-standard
  - ./.stylelint_wishlist.yml
  - ./.stylelint_todo.yml

plugins:
  - stylelint-selector-bem-pattern

rules:
  import-notation: string # esbuild requires string notation for @import bundling
  selector-class-pattern: null # handled by stylelint-selector-bem-pattern
  media-feature-range-notation: prefix
