rules:
  selector-max-compound-selectors: 3
  plugin/selector-bem-pattern:
    preset: bem
    # https://github.com/postcss/postcss-bem-linter#defining-a-component-and-utilities
    # https://github.com/simonsmith/stylelint-selector-bem-pattern
    implicitComponents: true
