env:
  jest: true
  node: true
plugins: [jest]
rules:
  jest/no-disabled-tests: error
  jest/no-focused-tests: error
  jest/no-identical-title: error
  max-statements: [error, {max: 20}]
  max-lines: off
  max-lines-per-function: off
