version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.5.1
  node: circleci/node@7.1.0

executors:
  default:
    resource_class: large
    docker:
      - image: cimg/ruby:4.0.7-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
      - image: cimg/postgres:15.17
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD:

commands:
  setup:
    description: Check out code and install Node, Ruby, and database dependencies
    steps:
      - checkout

      - node/install:
          node-version: 26.8.2
          install-pnpm: true
          pnpm-version: 12.5.1

      - node/install-packages:
          pkg-manager: pnpm

      - run:
          name: Which versions?
          command: |
            bundle -v
            node --version
            pnpm --version

      # https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - questlog-bundle-v1-{{ checksum "Gemfile.lock" }}
            - questlog-bundle-v1-

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: |
            bundle config set --local frozen 'true'
            bundle install
            bundle clean

      - save_cache:
          key: questlog-bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - questlog-pnpm-{{ checksum "pnpm-lock.yaml" }}
            - questlog-pnpm-

      - run:
          name: pnpm Install
          command: pnpm install --frozen-lockfile

      - save_cache:
          key: questlog-pnpm-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: |
            bin/rails db:create
            bin/rails db:schema:load

jobs:
  checks:
    executor: default
    steps:
      - setup

      - run:
          name: Typescript
          command: pnpm tscheck

      - run:
          name: Find Unused ESLint Rules
          command: pnpm eslint_find_unused_rules

      - run:
          name: ESLint
          command: pnpm eslint

      - run:
          name: Verify ESLint Autogen
          command: bundle exec exe/eslint_autogen

      - run:
          name: Vitest
          command: pnpm vitest run --coverage

      - run:
          name: Stylelint
          command: pnpm stylelint

      - run:
          name: Verify Stylelint Autogen
          command: bundle exec exe/stylelint_autogen

      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run:
          name: ✨ 🌈 ✨ Run Unit Tests ✨ 🌈 ✨
          command: |
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              grep -v "spec/system" | \
              circleci tests split --split-by=timings)"

            echo "******************** TEST_FILES ************************"
            echo "bundle exec rspec -s <seed-from-failed-build> $TEST_FILES"
            echo "********************************************************"

            COVERAGE=true bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/unit/rspec.xml \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: log
          destination: log

  system_tests:
    executor: default
    parallelism: 4
    steps:
      - setup

      - browser-tools/install-firefox
      - browser-tools/install-geckodriver

      - run:
          name: ✨ 🌈 ✨ Run System Tests ✨ 🌈 ✨
          command: |
            TEST_FILES="$(circleci tests glob "spec/system/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            echo "******************** TEST_FILES ************************"
            echo "bundle exec rspec -s <seed-from-failed-build> $TEST_FILES"
            echo "********************************************************"

            COVERAGE=false xvfb-run -a bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/system/rspec.xml \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: log
          destination: log

      - store_artifacts:
          name: Store failure screenshots
          path: tmp/capybara
          when: always

workflows:
  test:
    jobs:
      - checks
      - system_tests
