default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

development:
  <<: *default
  database: questlog_development

test:
  <<: *default
  database: questlog_test

production:
  <<: *default
  database: questlog_production
